apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Pk89JH3olCDve6mZcTGgmC/oOrG5qJ82OouxlYknUjWP0JYd5tWQxA==,iv:VFTr9fKYYQ+Y0/trui6vCAUuOFaAQ/3jB3Ofv+6vdVM=,tag:lZudQja9TP3MxQraufINKg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNXZ3VFNlenllUXJ1b3Jn
            eHgyK1A0blVnamdBbVFCQjhSV05IM0JJdmhJClVGeEhkeHEybzJGMEVmMUFQaXZH
            b3NicE5kTTNXdHdDWTlhTis0clhtTGcKLS0tIHg3MXFZQ2cwWGhkZ3dJU2FDdS9B
            QmxibUFFVnZ0SEtiYThtcUFnZ1Nyak0KnEKyJbsa6u3KmUcUSCMzFrxeTcC4jMuu
            xH+rSr3FXMapbo/S19dYjocs7A/looz1qUUSDKsJRJWHgJB5bEYi0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T07:51:31Z"
    mac: ENC[AES256_GCM,data:R6GCG6rAv/vgxp2kn0C3tG/ujE9DlnuGaWH52Uv5jE9PR0fpogDK4ftvmz2AozYJe6/ikuxGiW3Jwvz9khHS0kPwb+trO+fyQpVOvEcxPJLRMoQkeVthh+C29j2jYUyIjzQJCj4cvy79bWnMLO6u53A9vWwj+WxUiPHMaakI+P4=,iv:st+qMiDs3vsbD9ZgLXFNHCN6x3k3EX0sDFsyh14sWxo=,tag:KGKHq8PaucLr3qWosbSQnQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
