apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:OXlgYm1o+HMolkUb+x/EsYluEBPVoFpMfaJ1bd5JvXnI1+uAnS/+DQ==,iv:3q3jX8U7dlPzp8DTWmjrVl72p8kLXTZV5zP0UGylrS8=,tag:QlPCpw3plOv6PSWOfaOOgw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWEhmK0xheFJTSTcvSG1q
            SVhFekMvMS9wWGk5dWlnQytUUGlNZlpsYnpzCnd3OGh6bU9NRFl2UUVTNTBJbi90
            cDJEdUNTcGlvNVFWcys2TWt4cEJuSFkKLS0tIC9DajFOaVBiUW5PdmRYNnIrMkQz
            bE03em1ZOGFlMktxNDlTdGNmU1lINlkKDnK5fSHeYLLtK4r/Y540IIYtg684TAq/
            vJMJ980H5yLy1rFmrX9ZcRhVKAvqxGcJ3kydw21nHoNkOdFa2FD8YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T08:48:34Z"
    mac: ENC[AES256_GCM,data:rNZtsyR9rO/+uKKrwYdaSuXMN6Ygf/FKVptEenPVQeBzmD/NBt0/askoLTxw6osocqom6M+VSP3qu/PZ16rErEdBy/5fbMCa4I1rdUjKo2R/BElkxQEM9OaS/Aw6Dz9p/OYURAmJvAfgbovJ+bx73nrKma0y19VhH6WW7b7vvTg=,iv:4dCsYdj0pCVWFvzgR38ar39ilhPJzMCvgoDJI4eFeQ4=,tag:FfJWVl80A1PwLCf12+36yA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
