apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:0DIm0QTHVQ+mG/LBT2p5O6rcUP5hdx0C/6OmI3ELX3vTPHfrMrjBVA==,iv:k+qwZYiR4gKgwrX6MR+CMrxRA+dnh5Q/pod80AolwRk=,tag:vpHYMALXFXW6XqP9SjfqEg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMVg2aXRUZVlGUVFCdDlW
            YzJNbStPdXg1ZUlFTUc2dXpBbEtaLzlUUjNnCnpybEJ2RkR3NmF4WE1iMmVmdjFj
            WjJEMUZmeVRHWkdGL0RnR3R1enlnZWMKLS0tIGZYNXlqbFBYYmJhVU5zakNCUHkz
            aVVISTRmNzMxNjVCVjluRFJReDd2aUkKo+GCYTkvLrWyUhB6fJ6a0pNFAOZ56ggv
            zGrbNV7Igkj10va64mXQyM5mskyNJGEGPZpvd9yFV7L06kegnhHd1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T12:20:08Z"
    mac: ENC[AES256_GCM,data:xFKOQiIuIoMmGbkKuZMY3me0HyrQQEPiXvpZVSsS5MBOguGiAMAybnKmKQVja7sIxtWD6Ll2WeET0bhAkKFsqEazzAwb5valXVac9+fVOSEUXu8kZMQGpWMwGDLlcBZAy8OvvsjMUOvXl7bv5pI/FV1+sIAt798doZdvU4o/INc=,iv:A4B66pWwjBdGXZFKRsGTkJztfHkjq1wGjgEzyKB63RA=,tag:A9mCZTRAQSbY/YbsA0saew==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
