apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:gIkK2x+D3V5uEr4+NGre0XUFgik+XfXDwK62Dx12G1rkHY9pxZKpAg==,iv:LgTeg/y9L/RfNBcZqZITGSu9GeIS8gt+HS0PQoNwwRE=,tag:iuyC1vYHIcaNcMAhqzcpyw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQTZOQzB6dGNFRmNTN3hP
            dWV4UVdYTWs4QTlIa2NUQjRtdVFrSHZQY2k0Clk0TFhDQUZkdWl5L0xvOTMzaU5J
            YUlHM0N5YjRFZGhQa1p4ZDcyUlpCSkEKLS0tIFMvVkhKbXRSb1A2amlabXo2aFp5
            b0pVMUVDRTloRFpjUm80OGovWWQydmcKb+qULnLL7f/qfYhzMGI+gq+va7SpTWrz
            uImtX1H4HOAP0PFrxkA4b9g02Tu/1/b8SZjJh65AIiQo1fgjCYwa9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T12:46:46Z"
    mac: ENC[AES256_GCM,data:TZJBPN47eRsiq0tnKziCiT9Py61EsFBGqjUIlWJUnoYA8G2kWnjlgzPG8tXSSs4gRjiPy8ViBfmb21WbVM62nQLCXotP2KlbaAgzLn5ZWv24OsxAHuJk3vXML95R8iFWia04R9XTHyCChRd9GQzFAhKqxkgzrNmDdGJd1o00txw=,iv:Xdp60w82xBsnkxnY/BHh/+UXxAiKgb80VvpyOfhaH/U=,tag:r9PuC1i9xa9XxeI4Pb8HkA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
