apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:AVJu8NYZXItZVBqmlMuTLHakYo7Q2Z3jWs2qhmWczH6n/G/J95PjCA==,iv:riQx9xZ0a2hAinqya2PDx/m5hMzJ0PblKshzfKjs0l8=,tag:lEL8GF842ZScOxrfOcjGjg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNnBLblBmNmw5dVdqNFQx
            RHltc3Q2SUNJVkRVQjNwYmFpVkJNOGdXK2w4CmxoRnhJeU04YmpXYmlCOGYxODBU
            SDdKV21teUMvMFcvbWNOME1HTnlFcU0KLS0tIDlnTENOdzA0VUVFVXZUVjB1bmht
            RlJlWkJUNllnemloWkdyZnB0NExTOVkKtzxh0iu+btsWiB2dCmllUNgh9ZwVQLK5
            o5KjEQ3Y7EFovTnoh47UEjZNO5IsUUAAndIALpJ1D95angAHfrHbjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T09:17:43Z"
    mac: ENC[AES256_GCM,data:gdCMZChWzxiViHHInZgReeo9Gl+FrEYTzPXn1NeirKTTJ9613WoRBk3Huq2ZYB6DEwI/t6vdYsOtgBmqsh3aExcIHU0XN9yclQbUmmrrDyGx2nB1k0luGy+wZpwi3SWkveq0kMicnEflWWPxDUzBm1Tlr1QhosP3yhggHHoniNY=,iv:ZyKOm3zfUNKrTiooZ20DdDUKcW3KvPy3pYRm9LPaKa8=,tag:a1Dfw7v5uyVkMQt9dm8O1g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
