apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:d28fDK/paNjyG1GFGad/9Sjprp1i/ocqSf7/2h5HZb1C54VJLKXBIg==,iv:uYebDmQ48xCvGgZdSVARgcZ66cL1EcSlL3InvbKb8R0=,tag:Fpk/8WE4b1katefAVe5DZQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMlpqRmc5ejRxRmhJVDl6
            bVhBUnAxZ2dTbVhoT2dDYXc2RlI1dTVoM1FFClUyQzBxdldTMVlqVW8vbjJUTXM3
            WHFWNzNCdVFCUmZGMk1mN0JCOFpzeUUKLS0tIGNOZk5wYlp5UFc5ZStkdi8rVk5F
            ckRNOVhYUVlTeFlGcGQyZGxyTHIrOG8KU8UKp5kKgBhanjlj1f2nV4lFg0Ey+ktv
            xNYvCaYqNMn/OoAxaS+EO4fUlGHpVhDkLlXN6xqVsMLcBa1Q/2TrLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T13:49:32Z"
    mac: ENC[AES256_GCM,data:FEkloLBMHLhEYd9J7MhEfNMypfewplOAvJavwMwlmOPAK5DpbY9yvDfIjdJIEwNKarCsmFlRfK6iOdZY5UdSvuj/rBj1V+mvqA0HrbZSctUhZH0R1yY0gZnY6WPVGctZ0GyyskqLqjEDMzniDafsnAtA0isGpxPRK94Sbi+kKHg=,iv:q2J43bG/A0bpNeb3t/h7yKVoD3PmYW6ZP10uarv7C6c=,tag:bItmW738nmcB818zfp2ddw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
