apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:WMEUCLkpwCH2WT+HvL4S5ERgQ6N8uQgFuQf7hs5hP1rJTrgypnGm8w==,iv:MuLIHhJbb0zyd9BJ35PVKeveZzezHaTGbl/3Ku7AM+I=,tag:fEjIjP66o7ItZDh59EagBw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWU2IySUU1TVpGMnJDTnJS
            eXhnOWZXYjFsaGVTaW1jTjRJaHVzZjFGWlJVClhCZnh5SitFRTR0enM0cmRJamRa
            ckcvM2l2aHZhMVlpazgvS0orcE1pRTQKLS0tIHBwZEtzSGFBVnZPRXNxSW1UNDVy
            Q0dQU2RXRkV1am1xaXZ0cVF3SU5GWUEKA+wSz/MJMs6cOz8o2MtVNZJOOwQhvMB3
            2RVScMdR8JvQ5RZhv86qNgjHsA8U2biy8e/acL/ce2pVrhcBJ70IEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T10:46:44Z"
    mac: ENC[AES256_GCM,data:Nui0brO+H4QCY31RimzWkqC52Ddk5J2YHvcOqAjapNkrTiJ6+KXWnZWlXSLbZ7S+0F9bSBaFjjdTbFv4GOwZGlPS4irbGQdEeyWHeDED3o/Wt19bHN6F0BDGHSWlJpsOYq4Xf7H+IzmfR65N66w/YSdgrN/dyGkGWsgJ+VjkQ6k=,iv:FdWP8rs8IhHSyqDn6+MjvOtfcaHI2nruxPZ2UChD1Sk=,tag:6iU5KTMN3ayQLjWpQ7X1iA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
