apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:MLhD0O8vfQeGE5lfsYecaKGtZlsIxoGuiD4gNpgk9nPO/OPapluOhg==,iv:fGLliN6tkRV+npUWmQZIK4bafjN+5b+u+bgrpCkh22g=,tag:qtMofF8ES7BDOnjkSluYLw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2V0pzMnlYVjFCTFZhYTEw
            eHJHZHZjaUlrRllYVTVUbktHK1dyOVVPQ0FvCjlURVp1ZitoVG92ZldZT3BwQWlp
            WHRBdENCaHBLRlRPT2lobEFhMkdiMkkKLS0tIGVBSjJlRlVsQ1ZXejlObzV0QXlr
            bEMydklXNjRzQldoVFNRazQxSjBNNjAKifdcDrSlB8dG/tg6k5OaSGFHBwTVTQqd
            A+PFN4abn+gatmfYhUdtFqwQ2b/An8ljLZFxMgyw/LCB4aKQCF63Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T08:37:59Z"
    mac: ENC[AES256_GCM,data:AjuoH9SvZwcy6OgbikkycFUquBIa6df4kCJ7XoCEdgO8gBfXm45UPuagHXH8aKdN/zL9YKMoxsL7GovEDbnQmoAHV/H3zr6BZ5LEyszAotorLntM845dt7OV0BSUYz6a8b/jCmQifxy5ezFiKnfF6+GB1yzeaLFLHbF7O4sTy9g=,iv:TG3OmBU7narxj0lVkkeEiom0iE6wiRlkCk1NnWea1t0=,tag:EKP+Tmv2Npbx5rLvpYeL9Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
