apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:YW8ptw0WKUGy7dKdkoU1+NwthZFXXqZ3wrf3tjNUG3bYAcgv0/zmbQ==,iv:WOOH+Iz2dnLEwA/1k5tDgxmCNnt+llbEOgTkHJuq0FE=,tag:VY+EJYRVSspTU5bv+6fXMA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibVczMnNLWkZoUHBubkpX
            R3psQmhjWjYxQXpJbXJWU2MzQ2RrM3VTL1hjCkxHWXVxQ05TYkpEbTdjNXVBNTlK
            Y2RLbWd4Vy8ybWoyVGFlMGIya2xDSk0KLS0tIFZuTUl0dE9hM0pyRTJsdEVrWXNR
            UmlaZy9BbEw5VDNuSHYyd01QYWFqWTgKRQ4zTJMWnW7Wjy0MJzRB2CAFfPMlxiT2
            o31hf8u4dOF5+5NzfGaj41wl4zMvT/nsNHCanxuz6dUAjRqbO2aWuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T12:33:08Z"
    mac: ENC[AES256_GCM,data:iFIqgjtkQVL/DsSqoRCz8SuWC+U2cYdokwYJdJRGPG3qiUj0rcQVcr/3X5Qw4L0JRkxrb365j+A+nSW2TUrHqOM5e/Th+2cI9xGtEVwetMz5h4h82C2Aaht+V0Mt+bbBM5QeJkcKy/qQEqxEbq71gBr0YBbhf6iE6C9B1WlfJRE=,iv:yFacwVlDvhCjK8m/fluhuijaoRRRT4e2PxrjZ+X459w=,tag:u3+mnjRGhrqwX7OiJPD3zQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
