apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TCn4lhs4xof+3ZVSrKBNEJPKK43iemytzHPsFP46+Ojko7xDtbhBhA==,iv:N+QWvC0vMA2bfz2e6xMVhQwD3AHLsDvvkvJdds0TKn4=,tag:Uqy846yxLT2LDHcPaw6/4A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUXptYjUzWGtIMU4vZDhM
            UFRNTC8waEVmYnp6cnppbXZZT2JnbVBCMUdFClVkTmFIZnBGTVJvRHAzWVI0MnRk
            Wk1EVlArRVdWaFNqWHluZEI0UnlRYWMKLS0tIGloTUxFYjJhdFU5NHF6YXVpU05j
            cS9vNUd3d3lNMldCSHNVYVpkQjBvRzQKyhfU+Qhpx01R454VRqZOexsjy0kvTAfB
            8GtxtFFV5PE0ngeAJeRp3LpEBiczvFDWDevwB6IlEgXlzZw0H1VHgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T10:53:19Z"
    mac: ENC[AES256_GCM,data:1cyQDRkR38UVi2Qj12bNmQLkHB1Z3LXwPxiKA1ds6M5NQQ7GEfVj60ZwNUNJuHHng/TA5MHzUoMQ+SHXYCHQAawc7na6cfJInU0XCWwgdxRwVfdNRIGtgRM6RhJoxKC5H45aXJChw7Fm66MhuJ/Hv7an/1XzzIeP5PrqGwffXLc=,iv:ow6amULZjY2DxSNG8xy5k8dqUEkGmf3O4bYQwtmXSgQ=,tag:AOhuEjCnT06bizmDRwxl9w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
