apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Oypf6ebR4RSyNc7W4ApCzaKdB6ct5hn1nX5roecoP7WnA6T0FNv7tg==,iv:kEXg5DAWioTsbJIAEBeHssP0uAWx4L6RJFUpYE+FpRU=,tag:61TN4ehB2na5IJAhPyhNxg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNVBZekxLTHpGUFlRbnNT
            Z3d5OXVrZUFjaFoyMFVkOXdTa0oyVitTWXlvCmZKVW9HTFBnZnRSbTZML1FjSC9K
            dnVCeDRJTGVyMTUzSmhwNE9kZGlqMVEKLS0tIFNWQjRHb3ZSeGUrR1hVN24zQWhh
            ejVrU2Y4NEtFL1ZVL3NqQllHeTc3SUUK3k2fpU2zykL1Vists6Yx4uX1gNNuJ3EB
            FHefoyum7mCUEKgdlB9byRLyqjf84hdHOTDGvLdP079/Yip9H3cvdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T07:54:19Z"
    mac: ENC[AES256_GCM,data:EPx+4hZ1za5rswvyth0si5ZV3FAOAv2oivzmvOx4WqtJ7TJe4YecDAy2CAcR91yB1LfPPbeZHXArsJV4TLuAxN8Ji531IIkZqE87oi4lxQpl19XqKH7T6ZUwSBRk/TvYc1mZtShRGt6VbSfjVr4gGp7h3NeK4O3sxqGSZ+h1FC0=,iv:/t8OdWNDsDC3qgKJ2WjTBL0UaSy1UV+pPXOKlU8B0ik=,tag:GikvrNlAHrjyemoab38PIA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
