apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7WdJhcp9BpYBCDRPDkNddQ5GDdetoNY3eW8Nys9ZbslqhavoNnQYjw==,iv:xZp+/lNG2ROIKl0CKBCMmSyDDfkKp0GGVZtrnMIPAKk=,tag:xTcGmVmHC6EF6cQ9T79srQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM2F4RTN2cGFqMnhVYVlx
            dkxucmJ3YzJjclFxYWJVQnpHOTViVVdNUVhzCjgzWXB5cUtuWWhBSHA5RlZIRWl4
            R2FSMlh3R1o0OEJ1a0VqQVZvMWQ4YTgKLS0tIHFRTFFKQ3RFekY1LzYwVEwySXNy
            UmJzdXBaZHlZWG5PRURmUHFKc3E4UkkKc1/cBiL6zMNxxnByNN6I/PAs83j8S19U
            bApIlqcVwA4xq8N8vK86rIIjSQhJe6hTSkIiGjN1dxdUjBe5AtjWWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T08:12:22Z"
    mac: ENC[AES256_GCM,data:e80a7+vFpwHNRkDsuxIux6yJxnmkbvpwRPPjTPHqC+2S6ggqpYrmT5mTXvBwuIiaovWOVJayInhEMn4WxaT+Ndp9QPLat1xULClddFQEwOC088srEdemSZeFsj7zFbPV5057TYy2/jpv2ulSpbgBn38enLMBpIKRZDNt3hWXJRM=,iv:QmuchkfJRW7Y1PXThSrWI02B3Jun163UYsZ8/jNlTK4=,tag:Wq7P1tdUtGqZUTlgclcO8A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
