apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:qbShjtAEQI3BB+/JJhDHIlksXFVa7Si7VbohR0PjFe07erwFA8wDbA==,iv:ciU43zLzHwaRT0+7s0AA1haE68j4LtawNtZJEhGN5gg=,tag:xN+0oWNGxSgJ5/wvEnpVEQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOTNqUGQwSkJsZTJSSUgr
            VHdISkxXSm5aVHBtK3dqVnpFQzdRWFlJbUZ3ClphWHZnZXkvVGJBa01pT2JMR1RE
            THRwVDJrQ084Rzh6TVR2aXphcU5jclUKLS0tIEhISXY1eFdWaGlFcjFmZnFNYkZw
            M1JweEd1bWduNEhIL3M3YUkwMVlWdjgKbuIm+8NxagD1o/ZS/mMmUISFD3Jfxw/K
            41SlKsQZWLpXodHBH9ukZmPmz4sxewsT5pk4gRdAALBYypWkvv9siA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T08:13:00Z"
    mac: ENC[AES256_GCM,data:AWNycd3JWXtljqeyZQ91K+2YRkLK9Fjq8kyEtugQXDhiCyAysyftzoFo8fnujJNgTzPr9KnpKhmdejAC68vJhqjvbMde7p2SViZ7r/tA+AACPWdr2zb8BX39gzU7PBdCYe6g4g9WImG6YdH9iMUhYCrFGa0Z8/vSzHXrz8TDZqg=,iv:EVC+3fpp1yzqVM+FB25b6OJ9WZP9qjEINvjifDWgQus=,tag:zkbY3d8YAR2v/HgcbRxdNg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
