apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Afz3XCm3i9E+SXtUq9ULDnFc0otPdfcUJlqs8wABJgvPzb8nLjiYPw==,iv:btToXqrIisAoS+8zHyg+p2LOs7uVEGwrnL4jXBViaOE=,tag:A60N83uRtoTh1Zjn1U4ipw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQN1FBL0ZKN2d3WjBqMm10
            WEoraXJUdVQxM1g5RUpvMkcvd1IrTHZ2UzEwCkVyVmRZYmVudWZrOXluOHZ3ZHF6
            Q1U1dDRhUVl1d1h4QXRub1g0OE1lN2cKLS0tIFYyV3ROZkR2Kzg4RnMybG9iL0ZX
            K3hmeUNCVkZaWVVvNENBaURTUTA1QncK7GnrvbDV5vV4OwV6S4KI57Gl3yqssvjg
            p4vuhDUaQIMgbF8oFZiwE2VD4R0hgFN0eJJ8vpAUf9XwaAQGpeuyjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T09:19:34Z"
    mac: ENC[AES256_GCM,data:b4Zy5ljw1eTVv/GEQs9gA+Y8i7jYuLpcPERzX49JBrN8T3hIhJzX7WxrhkpNWfwIJSdsHMkMPmSD6qt+Y6TMw+sklE2varHdD9j6Vdw/AVTZs/F4Hdn1z8P5ZGboh3zx+P3j2aKKfCP3QhLMceI4E+ZciSt7SqpOo16403vqybs=,iv:ul15rKXKs1UQZHiYnCMwXQyZXF8ShlnwQlAT3Pk3hKc=,tag:KI38eXSbWJT2PEB9MOqkhw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
