apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:UAo7TH+3kqwr5WP8KhsBQuYokBJFPMkQK0URZX4+mDHbtBcwMJ1BDg==,iv:/BZ31CO1I5kzsQqJg/9Z4ItypIWyoxWX5PYQ3XeXS54=,tag:F06A8nJvsfVD/WiCsQ5Dxg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxankzbjZvcnJMYVU5L0gy
            Ukdsa05pYVBhQ21lS1NHVmE0TE9ab3Ivc3dZClA4NVo2TWxEa015WXRYdit6V1E1
            V3pzdzZnOHMrUExueExrQ2hyeXM5R1EKLS0tIFBHdzlHZ2c0Y1A1QWNLTk9Da0JX
            SEhleWpWNDZlc3JsbzBKNitZYzJFTTgK++Op/5k7ik9OdMW+ejKtjKY6HtYe5rKL
            AVTwj2KuYOCviYfZ7q71QJK/Mj6COEGVkpVxgMB83l4LFKvHRSazaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T11:48:21Z"
    mac: ENC[AES256_GCM,data:EjIe9QWwIoYVZsebm+T41PVFLq56yDX24eP/24KkTNIB6t6TDV4KSYWgNB9mOX1il9s1jjw6hxECQuKEx85tlsSltSLyQIF4YFkqPWBXge5vXZmglzP5Fp78xwKMwjYhE5ovIH+mk7ZD8IChw/NKx6nh6ipcVOFt7NJl6bvKk7c=,iv:relrwNw0HnIOx5zrd9+Lfd4/3x/xH82Pqicj+ANY5JE=,tag:FMJ1yyEm04NNTpam9U0DyA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
