apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:1yaUWZ4QoZhdv+BvpicMmG3MAERiBC8XfIVw1yzWHZMG9LaCy2AHmg==,iv:MqOoC1CPqgAx5m4tyRtwnCDI9GhOwoLPObWWl0ffsLU=,tag:o/VsimAHCYXMWlT2pAUUhw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUURxU0JpYmpMaC8ya2lE
            ZU91blZUMlJoTFdMWmsybWdxNHF6djZaU2prCmw2bDRsZDh0RVJkS29JZ1cxb2Er
            Y3Z3MEpFMHpUN1VRQ0s0T1lnQmhpNTgKLS0tIG9NYmVKa2tQdU5Xb1JQcWNFZ3Fh
            ZGtTLzZCSDdUM294RlUzSExsTnZhdHMKibDZQiiNLD+0+GZnwlYTpMDwIws7U7xn
            g+nwCSzHJaxq810Yp3ENHnDLRvtoR0MBX9mthmOf8nCyHD+ZHShXuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T06:40:14Z"
    mac: ENC[AES256_GCM,data:MFs2wFGBfSXuTRBaXAXZ64UEYzxUttVT9lChnHCEQVH0/ZxXwtfW0dM4TWVt8GH0frrjjDuP/PDFPvwNmLxG+37gY5ndONDQuOPpqHM9rsfuOlfU5NGE1VQT5SXWu9vkBYpvLtEimgbwMpqa8uQD9Uc/sg5OBOCt2Z3LF2IOei8=,iv:9w5Ble2VjxlzpcbROxxgWfw1hLXPHdxZnALPvf8cscA=,tag:luDaUGnFNKGR34UVe7pPdg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
