apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:EfMM4sW1+Cda6Hj5xxoeYrbxd1W0VM4j9LZ9EUGTVXGvDWVhozzPhw==,iv:uZmFLMjlzT2+Lzk4DCy6xyzFtX9CU83ngR6wH0+XnDM=,tag:Jt9wYo/Dcmf1IVjpkAT2Gg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWmpTZUpjRWJhVU9LUXdv
            c1VKb0t3OE5tdWpvVXBqdFJZRnpGRjBIMEZJCm5nMkVLbm5ZZGZhdGxuZm9sNy9B
            dUVmMC9MS1E3anFTd2xOWkZQd1hqUUEKLS0tIEdrNW1nd0s3ZTJoeFZ0UllRc3NC
            bEdLekZiVGpvQllZbDNHNUxTcmx4RW8Kk388UBeMp4mnzeYJpfDLsikuzE3v9XGk
            LORRiRWnidJrWePyrbrkqajqjT/8I8Lc0PipNSgOXqd49l1LgCT2ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T12:53:53Z"
    mac: ENC[AES256_GCM,data:hX8vwNxyhnhG5sR5k3dqYtfpLpsz5XMf2FPLXVpumaG0WI1weuXj9+WdQL7NetXjstb8zRRIWvxpx6ssqT1OfL/eygsQc/jF7xEh+JKMi3F6eUu4PW7TsDWc5BKoPI4PoQGjDQdI0UVIEFyCPpEKMRGplGgf54utacam204U/zM=,iv:cE6zq3/atRDlOFH8hTHA4kV0ocfYof2sbsnB/2vApY8=,tag:58+XflhNMawMelfd1UB7Jw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
