apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:zgRhur/uXcmYtgeQ+kggCcF/hhduUG5x3qHg4mg1BMZaEoo2jg/f7Q==,iv:DL9gfYpBfeJf31358+JM8jwKVhEL9oFeibyvDDbtK6g=,tag:IypegIHCjum/MupTHD4p+A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSEZlcnArV3hmSkJkaXJm
            dWFCSTRLbTdZM3gxL1QzNGtMRmQ4SUxjZFIwCktKTzRWTUpjTjQybStCWm5QVzlF
            WEk4eHlsY1ZFMFk0NmY3bzJ4aXFyQ1kKLS0tIG5sMFNFV2tqV1BUYUdVck9ja3Jq
            eUxxTm5PY0ZpRG5Qd1Fyb3NkcHV4U2MKb2veyHZcvCCgy+hR9cbf3hQOe5tI1wCs
            znaZssbFEnecimw4WkW6ezBHF5Ic8+NkjUDDTl9NnBI4EqNGmHuSmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T16:16:45Z"
    mac: ENC[AES256_GCM,data:m8o2p/kwVCWlWYFxrFi8cMP+kZuYhcL+6Vcs+lBfTOImCKzz1VHwm8CveM7c6ssSzu0G7DkQY2I1T1HYx6P1rFp52WkvBnDO22P/BwcPSngel89BNS7HGF2MdFhp2iI1EvKoFKEEa/XEaPnS1d024yB7hVrbbAcowflFliTdKSY=,iv:NrKATZzEgdj/CFHvImyV0mbGfskb2tNFcveFDNVR+Mg=,tag:GtHMIrwm5gKb21wYOuoRWw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
