apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:tNFx+MJYmqoHRP0hJaNclO4tn+0J9cPbC1JQ+1q0QjKnlyV+UUbItw==,iv:HDLcQ4tvRXnE9oHMh0bFZF3jHU70tamYY3eJStIr9FI=,tag:diDwvzBiIGjEE9EDmvF4yw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVk0vUWQ3MTlWNnQ3L3BT
            KzhhYWJKbDE2OTZyR1Q2Q2VYcHJMd2VLaUQ0CmN4MTNuZGsyMExYb0RCTUp4bXhI
            b2ZicEREVHBVWEczbmw4ZVFUSVhHS3MKLS0tIHBXQ3NSYWZCZjlIQzlKdzBBSHRF
            WERDRUtITjd4V2lpQ1VpbW40M3hNQ0UKH2E7R8908lt4dRn9j7YTHt2st5cs9K3/
            zT49SsCiDt6ehCF/+oPZUKQdXsiEfLFa+JNnf1KbCNXgxHCa6TmABA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T09:01:37Z"
    mac: ENC[AES256_GCM,data:FJPcYIGfz9tW5Vh4joUaMKluaxBfMDbaDOQ1bnq9RUoCQQ4JUfMp8frfkbyoE+u+VSNgGEJBfH3mw6s5TErRPsUAzWZiE9kV+cOBV4cASgkiOjnuoXQbVWuoCmRPR1MIpVM+5cRNsNwQ1zneokPZsfmYjvQfMJzYAmbIEeyNpWc=,iv:ff8Tt7jyE19nF0GgbwOoYuKOgX+Ka2E/Cit8LoCAzxk=,tag:kZgvmRtAfYZq+MBxJ0ttnA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
