apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:2gZnw/PZLCJCFlFBpPMUeBKL9AvtoZQbwHi4ipUsy5NsVBDR6GK82w==,iv:ihHHQ5WLY8zk+f/rb2gAmqsifzsY9HldX35ckMKaS2E=,tag:IDA13pOKiMR2caB1i4Q+Uw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQ1JTc2dlSUhnaHVkM25U
            T1F4bHUxZkJtS1BwNFQ2bHJWd3djNHdiRm1ZCkVoTEtLTEhqWlZGZmE3SDlsNlNH
            dFhDalBZekg5OFlCcEg5a1NQNHZpUFUKLS0tIGJQSlpCSFNDVjZ0MWU5OXBSbHlI
            SzZnNllaMVVBb01rMGNBVm5GQWFCOUUK9JeMM0ncXAUhPA3oFR+U+BKy6PJjdfaM
            unQ4spzgFdQ+KzBHddTNtbAQjT7F+Vo1sX+j6Fw50ZndySpOROSBgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T07:59:44Z"
    mac: ENC[AES256_GCM,data:xtIveZPvFuXw613aVuS/kpMgIInaW4BMHx3AbX9exFOaXdObklPn/6Ba1EdG9oMvkBOeESmTAk/PqIzMD8INRrin2S3K7GG/QuOa+hQY7Qwc2u++9VGKo9wXSNnZldcF4rkeyGmoD1Zhl0E2UjWAlFJiMW8f9nnyV14KjU9uL/Y=,iv:151YXm7Fbyz9JlUmMPuvShnstUgMIyidz/oZuyIO2Qg=,tag:yTRW9R7VgO+zfNpGtaWjuQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
