apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:9+DtcGWubG7NRXfZcgywPuTA3fCRfl6u+2MfG+baDOzXHicuo3eFXA==,iv:Hhd4Y1VX+4iUd77F85pHwVJzR1jVznyByFSFNxGXfDk=,tag:+rL3BcBKLXtpbKUYL6rFyw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RmxaV21yMUdyb0xkU2NH
            dGRJYVlKWUxWY1plM2E5dzA0aTRPNDBVdEhVCks4M0I1OURsWG1KZ3diT1NCYUFC
            TVM0cllIWURBOTFLcFFmcTE2RFhVZmsKLS0tIEhkaGpzZ290OElBT0dTcVc1VFV0
            czNUVzhFdTZ3Z1V6RktsSStwb1VnTHcKKfYZcVDzOAcJr/EesXxt5fsM6fagw9rk
            /tK7xyd+87LzoufK1NT3bkhy+Rvbto2pdiSbWmQq5Rwn8loe691lCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T09:34:12Z"
    mac: ENC[AES256_GCM,data:l0yhQi1jMYvJOo3vMSxfyeo1o84fhHk63vNTk6C8dADy6vWNNj/XOrfNfs6GwXFLyp8Lzjw2nf5hbenO1b5+ut3dPC5d3vEjbt4c1m8lyDlnDBAQ15jcr0Nf261j+CbOXJBathjTj5WLCOMnQcmZulvUJIs160xNOYpIPxRs/mQ=,iv:JDiOys7mMK2HLW3JerlmBiZRyEXARl+3J9FtXKttw50=,tag:nmD5gPDfVap0CKi4WckRNg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
