apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:OfsmmessuRBzAzT3kupa1t0TS6rUMFEZd6g3Xtn7QphsuTLFxTzH6Q==,iv:rs6Axnvj1k+N3d8IJBZN0CLt6NtH1mtvjitPinjq20o=,tag:MFKGTJpSemANsdGqJVRk1w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRTdSNmVzUTBJZ3VzRTVN
            b3RyQmhPVzMrK21iNWppaUFUckNhR3I0cENvCnEzY0htYUpFMWcyVHFOeUxMcG40
            ek0zQ0JzTmd1V2ZRTjhidEU4ZUtHS2sKLS0tIG1SQ0xTVGZUR2dYTVFGNWRFeVFE
            cDAxc3I5dWxFTFJOYlQ3MEZJR0poVUkKQTMckqoQMc96kxpPBp6mRSt+WpJI6JvS
            N57KmomSFjAeSI0tveXeT82QtLlsahcb/pCYEIh7b96HAEzS2ESJVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T09:28:32Z"
    mac: ENC[AES256_GCM,data:4nkkzh1ovfkT9NDyvvVw0ug1kd8CJ72GSaFFO/sLf8GDk7MX1QHDW+AKJaquwvA8WlMHDJ/6rpLnXeh3+UhfOFuPuR2sllLpUbBL0dV/srXy9cvT7JBUSW8sT2rHNq2icm8JXQ+dcZsUh2u/05LRQ6YjizCxUdSXfq+0pvPyS1o=,iv:7dsumiqLH9xLLSXfT7BeEA6btLw7DFMETJ6CGcDiqw8=,tag:v3iVcXXQu4jFNkjg50I5Zg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
