apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - borealis/ks.yaml
  - cloudflareddns/ks.yaml
  - ozrates-static/ks.yaml
  - viminariacom-static/ks.yaml
  - wg-easy/ks.yaml
  - minecraft-java/ks.yaml
  - minecraft-router/ks.yaml
  - nextcloud/ks.yaml
  - ollama/ks.yaml
  - spoolman/ks.yaml
  - metube/ks.yaml
  - uptime-kuma/ks.yaml
  - myspeed/ks.yaml
