apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:F6ojDPJcw+dr/DMCLAeaAbK7kSZkGrVTmuOawhCwHACf7ofrXOa7gp/2vYXMZxGMpe++CMq0qiq6U/ZlKfD/p+2ooNfv2Evy5aQucezZeWLISEgAPUkajx0fFhte8DN3iO8cbxyP3KiZROGc9agsMhKMt9Wo+KbYqvemqpi8N+QCstGJxgRzJZTziOUdIcsffBWrnpdpj1Rs5S/7j4fasUE/OZwUh43hc3J5uxrryYxnLA9bGigvoOpwKDbt8KJZYX1RqtjWNwdWwARj+bs7tnrpgECh6ciUf+D6eYDCg7PxQ6Gpi5ltOuALKOeDHz/caBlnoIaD0r4OfTFFzXwZ9TEDCGSOsFjlndpx1GrSa9rXKO2Me9MtxU6wMSOwLEVx,iv:kk/1iNGSgOnAW4lwExQ1B757z8DNst+MP+624BOMoFc=,tag:wPBChWF0bbtLZg4hj4WDWA==,type:str]
    identity.pub: ENC[AES256_GCM,data:c9P9p3HCaZEVDCKId9HMJFlmun17H6i/TzNBXjS3H1hf4zjwBfVJI8q6aSXaTzOGCt1jzpJ2lrRcHCtD3x87dddSUCWcogffyshaQ+KsZfgXnWd2YAdkJutEMxcbnBxs2iOa4+VKfMop40BT8t0owmGAB5FCPxHh8Oggcafsb1cyPHwvx5n7HrA/dL7Pmr7tGbzmON2etpYtSrGqK7ufBO8iv3sML0f3NVFbZCidZjbrbTmwvTVWgJydLEv0SiotmxJ9A4nPPwNkCHe9Qg==,iv:WTr1ChJtF9+6lRLSPXTcWVeaIqPL3CpEP0u1K9b471E=,tag:Y9MG8e+5rIrsIQqFU+Emog==,type:str]
    known_hosts: ENC[AES256_GCM,data:tVvMKQALgb3MjOnC+TUD9xsHZtLfd5gpmSPKnR4FrE9CUbAmNVp5JJ/HJDI34Rz0rRNITg7o+ESNGNom8SSa65k0yfNtVBqDIxPB5vZogviehbsIYRIIOEumv6Ff0QpdHO1hpF5nWt1uqDz0r5lVfj/Jpwe/nZdc99DWiZ912fn9lvKeIZjVWp76DVCDGQbrCCJS5PnNlGjMXkBTPDEhFpBhSc7cr2Xt82VB,iv:/vJYi1Qj1Pj3BnfnSQHT1GdVxXYMr7JOMOmI7rD+S/c=,tag:47YVT/qPzTkKEqeFu2A/SA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYW1uU0NQUzFoREhocjU5
            TFpXTGxnUUJhRWpHUFdZc3BQMVpmdkNhTlNFCmM1dE0yZmR4L1hnMFl1K0xkNlhN
            a1FHM1B2VjYrdzR4ZklvUkdOdlZHaGcKLS0tIGJxMlZKNk0xQ1JLTHp3ZmoyQkFi
            cC81NEhqLzVScVRCNE9iQ3l4NHdWZEUKxxld42cyv0zk7aY3DFmUm/YWcVzJAXaq
            fmdnXvxdqUCnj6rMMJWohFYUe2WY3W8JVRLVb1AT98ZYmRT+v7s65g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T08:37:59Z"
    mac: ENC[AES256_GCM,data:pNHdbxKOSRaac+X92T8rO1fMth4JAEkENWkgfBcMgGofz17Bd91GlC5hn+v7c5ljc828NyDksNX92OPEXzCHSxi6c/FbQ4NypnEL6GyAEQQOv/3XxI0JDqAVPjaRJIKYJkYQuI2y9XejZzuiZRdZavGpmLqQUqJ92DIBlrR0QD0=,iv:bDpWzEwzC7alLo3GvYj+K9d9RPzdJUWQBRdSGf4CjTE=,tag:mLj1JJrZvQ+En7UI45iLFQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
