apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:y2jPn5dk02sDPNCmoBSel8oG4YM1nH1OmSyB9JIn4IqMLfHrsOtJGkmqsVZ/pXlUsX1pix10NrLg+gSyCoWnmFffverFAymkSMf9sZ7fH+yUuW4gnvh8pNWcrSuG1NnRT9BbO9tB+gRDxJ05AqC0FNSxgoVDFq1u/H2J5WyUtR2ryvH0nX+O533/eb/B6WmGv8nTIh26JyNP5a6p+65K/v+tn86+h0g9jofN2ZrTxE5i9L2qwJMpXM2xWywIbDBXTojUVLCBN4AUk8j9Osed7oLuMJvZPN/XEcO/7ibtKRCWPN4t+B2EJ5xrVPdSWPZXrqrpMclYF5Og1QEkuEVq3K8zKczRgMuG+al59DpaAWW+uXQBP7CZXSS1eITW83F/,iv:jqpTm2XYC4PEa3kIt4QBF/oDxw7DohxNCbiXgRLhDpc=,tag:RslNN7WEqLCU4QwfnT62Hg==,type:str]
    identity.pub: ENC[AES256_GCM,data:uLNgUTEdA4QjB3TJOoZKml5C6zPQuUMhm7QCux0jRIsfOlpxsMjsOgWynN8goYAFwCOvPRLC7GGD9hXHE7+7cr5JpT4pt+jjyaeH63B0pwQ3e9cuTAtVIllC9FnWPfIWpZPp7pY+mov5ewrUHo45QRDGO0Gqs6D6LMtaAoUZNqF1hTz4DlQ2DAlfQsEt2JIR+wjSbUKc/ngmDORuEzpNuWkD6+m037brreQ96KY5kRCtZu4f+Jjz+rgSM8hwxN55XawV+lc1yyjmxtmGhQ==,iv:FcItzam9fVyjmEmokK5fATBlz79cOXlZT52dwmG/9lQ=,tag:bfRiMCH2Yy/6mH/3zN0p3Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:BTWcm6fECAXZLri9K1cxgI7OA0QrEfYw3QSodRhTY7Z9tpM1fZSu2/xxdGIhMc5B7a3rfPjBceaIWc5X1yIqROQ/zJyNMBrRxYx9bKM+fz9Uk0am0ze8APh5uhQ7lg/p5MXVrR4AuRzuiXNUAytYa62K1wcWUv/IW8EzBigeuraFdiMfh7K4u1iJMLPIfNwPyQg/hNBZWYvY3eRd9NHOridm5Kh5Y2NP76Fd,iv:kDkHRwzjGQD4dfcC7ZIEP4STOCHpA1WeRr4s4zy658Y=,tag:jEPyhkRzZRjTvMgnPU512g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSExnVk51SHM0WjBnVzJ6
            eG1nVlh1enlleWxOY1FhdituRGRacUdYOVNnCjdsS2tySXVtVEVwUWsyWUVLNVRo
            aERlWFBjaGhnc1FHQkUyRjREeHFROFUKLS0tIE9yYmtadjJ5MHdXVW1vTnVpWVJU
            OExjZEJ4MHVKV1ZWYlkwRTUyYjVDNG8KXnlcXjS9SPSK6JiivBCD//qiM7ITuOQ+
            PG3abafoqRGVHVJ7Kg4rmsE7VB6kfL5XnYL+gJzprs5BAfQtQbt12A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T17:28:50Z"
    mac: ENC[AES256_GCM,data:wkBThtYc0cX01Y0+52VBrt6R0x9URwszF20oOTBmtBENBQ2MX0LBhUx0VZMkPNGLyRfrA1R6kK26O2oZUUKklVzqsqL5JYJY87bVIkINcWWcbzU4cXKTn2fhRJKBAfcwlBn8e79ttAku81jKdMnyTxbuTXiQAkKhkixrxq8xqr4=,iv:6fEl24aOEl0YHo7wHALuoucZ359ELyGoD/P3d+zMaEA=,tag:emVAAWF9zGiYs8TQSmFvVg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
