apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:U4KgbDmdPcD22LruR82rsVo6XXLR+A534H9dlUw6Qj7JU9uOmUDlIjj1h+dRGypoAtnY0ViqQkhdikR3EZrJ/++JLrL4Gyvlp4T4Y8aGJX8EoX5feEp5A8Z+84Lkh6bmEdAGfGkgspJxozeYlJNbtrFPbvSUIwGCCetpcrHPqOGCyAbY3M35eAEM0UOwTEqJ4ByJnGERD2caZOg6+2aDGB2xKIvlVVF7lp9t7Cv4ivznYAUrtx38Qtt+CS+20YijLein08c5ttRYMPbaDL8ep1edLivBeAjLjc02dxKw0DzrE/vcpNzpekEEgIH+xxSYyPQBVRdrRt6Ng6S7B0JBVw22CILyk9UV62oJScese199rpMnfjuaemvh552Aa1GG,iv:y53sQ3F3GXLeKpp7v0rHpBffPUrVL+bQ2gRcEWmZSwg=,tag:h1w+c+RtC5CX1P8pLx1iWw==,type:str]
    identity.pub: ENC[AES256_GCM,data:WJVf7C16wC3mJOO8V3RsDnSi1C3bJZaFd/hCLnulJcZFTo6n9zlgxxuE6+lu/k9CQZBRdeE6B/efXhpZpkk+fo4zn1M53oNVb0uXD2sR+e3jafhgNTPZtB6n/fBokHAepEUmY3tzWs6J5LEEu5t8SBFF2dPeoHmJYQI8kcJ57Gw1DisS9nRSs7MezoyHr8z/m5s1MukDobJG0IvgkQWoax1v2dY+G4NgO0mw3GnKZiAE8XN2QTJAZmMXMYzUTntEiUnrDHKt5bGdGYlsLQ==,iv:MOEIKryCyl+a2iS936Uw8Rhayv3hQ2f18GG1m/SPTOw=,tag:U35lUqfrof4l4gM/EwFS9A==,type:str]
    known_hosts: ENC[AES256_GCM,data:aT9v5yk9mHUuZpGv30Tt11Gv3FkYLiQ0WIuqRJNnWTpgIMXiRvMRfgzoluWbwbrFwe2qvqpQcQAI4W2OHSj5BhYIMCNM6GussoqlCiRhM1vbACcM6dzbpsPhVLKk33wQxGzulKPJls6oCemvpxpmpJNXHAy1q1G3WQR6DPOPiXKFpoJWkpBqLS/8OHbwhABWT69gHKxAuY9TaFGYsz/qUeKh70ydZ7FZxUVa,iv:tGfG9JQ4u381uFo/t8aetbgh6VcNEcOLgo9bMNLL/+c=,tag:K2aCCKyCHNgraKg6InfY0w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQS9uRERzNXBWcFc5ak9M
            SlAxOXBOVFlVUHI2dDdlQnVTTk00TENZSG5vCkRYVHBsMHFIb2RmRld5UHBxaThI
            aG92dTdMOU1vdUkzM3cvRmdUL0FYeDQKLS0tIFR3Sks4RHdvRkE4bkZCYlBMc0c1
            WDZ0dmVWR2IyNG9pUTB4TUdYektuUU0KenSdY3u9SI6iVKn1bSuydYkTNjIAQOq4
            fuvZ8OHhWKnnvYQw3GdRM37hujf6cBYith7dduTOiHG4EOP0cU1iuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T08:13:00Z"
    mac: ENC[AES256_GCM,data:GnZ5343VyixRG+0uZQoGE2euBga/AXS61C6V/BuxaYu+usYRpsaDezAfZIKXMEIZ4MhqrcQA8G0Uh9hiihzrYRlgI8/rTW974VlARbH5xGud0l2HGothN/lypyuTgU/oJ8JBRWujLvmRw0fEjtrPCVROkk2uNGgA3TQ5BPxaAkI=,iv:FGk4JzDzUfCRHcnSCHqF15+Ht1ZtU6trmqkbG6cFMRc=,tag:soEg3jfJwOuN4nEQknuGzA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
