apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RDz0Xjv4ddk6cqTFGeIhkCzog3XaiAoNfW2UdZzpatzNVske8LJyOuW96I4+5NDAd9dqD03Et6ZzeaAl9lhzcJWXpAypH3MFDPOy7Cmk2fwaupjfWCNVbw42YB/KBO/9yjGXDlylJnjoyApGXjVee6eAdQsqMSH/I1nWH5mCrKg8ZCVn51jSEn4hHsFRvxwp15HkBGYScDItuKiuZ4XDk4gGsKtUeGlFLVFAADimUE3vVYfngECCSoQov02rZFrh3CTV03Z+Wh6967GfDNzbsb3LXfe5n0ObKCzJkdk1oSonyRNGr8BtE5X5SfWHLYbePjnWXyNLzAu8DmrDr3nrQVWJzoWzsmiGM7g20tbcG0UNjxygGotElNbL/JCJ8ZEq,iv:Xi8hgMmYhsU4GHSavy+ohY6XvctgsoOrO0KqBtk0Nso=,tag:tJMm5r9XBkZPKas6nJ+ehg==,type:str]
    identity.pub: ENC[AES256_GCM,data:dW8cAAHQXyh63GoQ84TVYTO4IWoWqVo8zyJcKwzo1fRhbRUBk58rh4vpn/nsPnFsjmjM201JV7dplnLjjW2OstqBEm1EQE4J6O8Y9sNNEFinF5RY2RcGBYKvSbzY1TxtBmFkgYFXlWajIjAt5cLXTCWmh/VDInexwNt6cw34BwFu7DxcHl9LajUc3O3b6EaouiVV7Ow7dJJPoNrMVDCfpfuSwhFIVnCzgF1pvdKxcPk1+7NiA4ZXL4fw85bqWC5zmzM77dH8OqkJWZ8ovg==,iv:aHf3QZChyAEo092KQRK98hw33pA+m7287BvtTMpY37s=,tag:j6Pd94s9VlphcFEdZhWiWg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZRZEZHS8MWhmSsiATut6H5e2gRg6xsO1Sd+RoNFa7WFPwBdRPkrpQvsEKsaNunH8AUdBsAAvR9a1lH+rb8dDuhsWs+uom3+wjip+7WPpTW4k540rLbHAHf+rT4nT/i2q4X8AMZp/V044Iov8zmTdgRm96OH8Kw01jBPuiFnIqXr4w92Yc+I5FYOJwFPLBwcS9PsP5+oguNOcvZWa7ibQCVTdzypoMWij5ju6,iv:Hua0G80gGHQVOeI2ojp3XMUhE9qR3vdorMkpSkZOboU=,tag:G76H2xAY+p+r9etyEKSWEQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaUpFTTZIK1JCcEdjQzMv
            ajdBdmUzQk5NWkJtMEE5MFF0MzY5Nytxb1c0Cmd6Y281d1U0U2d5VDJkb3oxTVcv
            eVY0ZmhxOHRQTXVmamE2cjkwcHlYK0UKLS0tIFR1Um5pZlRVVjlHWk13ZVVscmcy
            VXFnVlBFcWhkekNRQ0p3YXJqVkNsSTgKPzZ7a/3KOkd4j5OSq+2AdH+u2iD86k8d
            81nYxVTrDnc7O0YXUB0I0OoPqVixqK6CIGLfJGWrT+hFS45p+s89CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T08:48:34Z"
    mac: ENC[AES256_GCM,data:z/pSCIfF0b3ijHcBy+2gpB1YQ9mTq/9XeVLA1g1if+Kzd/JaikdOOEL3mu2Ke2UweJZKlb/twswWn10hHz5iAb8O7ZQYrXp9sZOKcmpK7UrtycDZSE+0LHQlx2pmvQF7GxkUfRCmQQClpr5CQAEmo1r66sgQosXVCBDPOEuVnjE=,iv:7JsXL1cF9cDWUBel8CjE1Drr6iXONPJPaL71fzCLPH4=,tag:5jBs0JYPOjpdTHicBWs2sg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
