apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jQUaDNL+hz6HICA5X6bfrDRgfOZTEd9nIpUiIb64Xj29AF8BHMMPsQh+KEYkKjIBvQxSBECE5k2YZDGeatBNJr59Ne5PRCUscjIwTd/OxNjbbzYkBlMgXfvhqkXr4j6SF6JgqIWoLiy6Ik83KppT3hVA3/CoBeS2xyyly82wb4hNel+f36irGwmNIvck8k84GaDI1mUcpWMqcTLi9KahBH/VJyEQVjeL07JYOvbH8oXkEZylMaopTvdaqqj4K2pNPZF9Yy6BHBetyVNT/eFBGjaeFBhDAOAn8H1Yjyj5/ofnQm8bwPLEWqYgMZMNslMOMveDR/PDmG99RxoretE/ma3wm5RM9wnYUTBEKJJGLw7DDP4Fw2PA2Dairygi5zvR,iv:HHOdeb0wr3z23FZDWeAHppE1oiSOJGYejc+xWs0xGFk=,tag:oY8fKxfja0B0QVzWUcJqjg==,type:str]
    identity.pub: ENC[AES256_GCM,data:3ECS3ODmyZbk4hzExe+Ms4FhRzK/1eZL0lAXRxeLXeF6ZesfQ2v/gRb+C9o0xRO+y0SSt3Svl1EE3nWfJQYLAabaL2GeNXN+OFA+KCod6dCjSwP8lihJnWiJPvuACVSbH/4XADCN0PMgYdi7Cwb2mR81XJPjCwDQ98zP2h1jE0r544P1/QJ1s7v5rToCfAdyzI9XnjEQX26lRs7+HzbpDC9ShFb82rjMl+tD+ZvrON0Cd81Vng0d/Y68DwdcHwpta+NchHTTKxaPftRolw==,iv:c5wKYdT1wUw2kUt3hc9fONZlx3HDUe5o5dB3xW8QsaQ=,tag:kzFgmJlKmZxo79P4EhPTeA==,type:str]
    known_hosts: ENC[AES256_GCM,data:zloYxDLBrO9d7mzjhbb5VykbjaVl+DDrjcT/symlzMxlM1heoE4lYRvLvJePFhP5kEFZ/TqhTlJ2yoC2b8miDNPzrpbpZc0fPtZ/yVt0ZbQTmurewwtE2rlbsoWu+RzLKUpIrUhZl5aD5IwR/H9TCozDEq/QmdnIBiLcpLf4c2TiT6c1J3tW6NM/hAoIJbVZMScZJiL/UlUSCOlZHsl2oQhbAOT6H36PSVm2,iv:IWO4VcHYMPEuvkSyNhKX2xydi/SuxTqmcaozfISLR6k=,tag:6QfbtW9PWVQRv6SjGUNjcg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSmQ0dWlwcTZhNHRxSkR2
            ai94elFRU0l4SzRLcENNeHU1WU5wUkVGOUJFCk10T1hxRGZyUGtYUEJUVWZFd29D
            aVk1WXJlZStBcG9RSWFsZHBXTCt1ZjgKLS0tIGp2ZVhJZ1dtTWVRYVZZd21jZkZD
            QXFuTjdFQkx2YklTekloRDhmK0o2RFEKuVjRkCEZPrtKIC3iaIZ0Z0V8DSLsuRRQ
            btA27SXdLdIIHS1oiTpaXc7Q42FN5CHNL1NpQN+aRrq66nQF1woFEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T11:48:21Z"
    mac: ENC[AES256_GCM,data:FU3CFfg1nZ2eJ2Kt7MmPuaAJsuAkp9/UzmkrTP0Tn2hiC4Iiw/6gEuRxvPOPkbLQo/rxj2IM8wiAxP1tZ0fjYF2OZYVTvff3BEAj64LgmJGnQen22NcS/U7iESqSx+DZgQ6lXH3YdmGDVTxeQJuxWtAJxH1VrjR5fVDVoftWWa8=,iv:dWU6hR+X8wJddjMwZhdad/2pF4rFMYWfqGMeTIwzuBs=,tag:5VsDf9KC09z0fobeTYeF+g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
