apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2XeB7TptSCpR/0OYX46q3NVy1hjEc966VB0bOsTjfMwxUyuGgeXwvKs0HrCyh20HJLVsJ8jYMNQBIEY4aqRUNTXC0KTqOblbsWY1LJZHLd4mVhlKwwN+dIJs7HjQkJrwmQmU1UM5cfbjFWp2WhvYwy+URYG3KemZBCdIpcNdTNlld/zOVTCdOlfKKeH9DaRydUJddHnkLJxjd+RmnFJ2fKCg13UENRxmCGgm1WUo6bNYR5U9Gb/+Bo/86mUwrzjWeIv7kshWAvcnquvCMZw5qoQi1tIJeSw4m9BlvnW3ufVZ6yoBWFvBTvpaApgeSBdQjHTLQ5nlTsjRKgNTDY57xnAN2AOqhWNGo5hCWSiLlEnqDEuhbn03YZ9NC7Nse6x2,iv:tNumRS8evyHrA3Ew2vIvQh5qRrgvXFvX52YNT9GBbeQ=,tag:ws5+ZP6XOeapjXKYdUUcXw==,type:str]
    identity.pub: ENC[AES256_GCM,data:JkWVBJUZT3aPX0PKH6tnh2w43MqTDTgmEdtZKw0i2XrFlHuhrCi+4g8tinvjGNsh/tEXINuUXrHTuX68bFw6o7XRReQt/hoz00nWoiG+x/eQxGnrXkCpjHGd+vTOJP22MuYW3/VMj135ub4q0eh26H8QSYO/4JzBFtp6d+TK6wemm885C0xkItNFzz/5ZkPz0aFswe/GrG54PcFoC/J+905G9j/kEEjJ7yqr/7ONX+A4u0uQclFCfvHUIIihkJ38ArsclhUxrkIOOv+lpA==,iv:TqWFzsNHmstHUgnvzvv2hoogj3hrohKuFCInTkBjGNo=,tag:vBzr7VGdtoH7g/0E2+RD2Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:2/uSUHY9P16QAI8fGHhbt5Bmwr1Ue4SgEJnN2su0Nl553LyRGSNHSmwvwpaZSj0089WUu8aRRtJ4uPzHpdWYUDK1848Il+Bd2CaCS8UyCOg7kena+H27Uu6er/1YLI3MA5iEEbi7FOGbYUcyafwOk9X5neMJGVBFIFo3D1OQks1pI6cZYCeKx8HKt78ky949m7sIlqvN3Ny8V1NwEwAiglpxlsXb7fyW7nH7,iv:tJW6YmC4YGy84IUUdtmmZnLIKKMViScUD03WzNVIa2Y=,tag:lPF0bo/zLrEDFKEJlZE0QA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeWJMa2tXWkxUNGprU2VU
            cFU4ZFlwTS9xNUtrVHJPaHpObzdvV081cUVZCktsMFMxTTJ4ZjVsaFV3Q3J1L01V
            SWhOTDRHRVJjVFdWbEF5WmZadThQTFUKLS0tIG5OYWxLZlhkckt1TTg0VUhrOXBk
            emp6TmVnSXJDR1NuRWtSQUJQTDdPTzgKIWN2IUNK5YOFAOWKs9yeiy1PyQvXSmc5
            1rzpur5vi0gorQqlHp7aKw+JDt6+HfKpL1w+VnFIs/CNZDIWrtdKXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T08:03:59Z"
    mac: ENC[AES256_GCM,data:bPzPrvXlaegPhLs3NknnH7Evo1JGaKifhjhOv19l2b4K9f2/dcvOAcGSs8zHdNkl4ub+9KqOm2+IENWNqJKpiQxzX2SDwEQTjxfeqwqBpkYPOC50xkUlYd//aGx/cfO7DHySGg+XIhsVPaGF3XcpISZIZKwlLbX0ahl7YjDYHtw=,iv:MYFSa2Owdbq3caLpPLE5OJ1o4h/lrIvocagoKPJWS/Y=,tag:gdRT9bL39hHMh7CmzlCiKw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
