apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:APdlzrdD64fO8VnaHQ1QPDReeUaJLUkrDZaZobiAhS8fK3NZjEylVYrwwVRPLutg0UoTq709W0AcmOFksnidMecqCGb+76yT0KgQn0zuJXNHnqfZ8/h8vB465fjnJ80EG0SGQzfogVWidzEC9vhl46WZAJV545fQJiC0dXM2aepZ1MKZc0Ocxc5NqEWRNqpCFnjlRdW83BucWe3Tps0O0OxztGWEc4y0CtQiqqMF+LJyt2mJ8Dwdj0XqZVx2UXacE7R4cCek89+n/MfZxHP1TJqPQjb/xW4/hvm3hI1hX7mD5s0ZKl0W8C22BYOpZj+dm88+GJd0lPX621zbMSuraTFz3vUXBlzprp/gKSkuffIf1JXNquRQjCwbVbv0WX9s,iv:a+Of5fK3KqCh4Nc9m27+x5sMCIOjnRPyblSuYRh3nXI=,tag:EOOME43MeD05eUtXI8Z/5A==,type:str]
    identity.pub: ENC[AES256_GCM,data:Rc/UkVYHAtJ/Sc9l+EUpFkbM2PVlT31Dpq1kXVPbYh2u0EiOlWU7KK5QjRxB0msQjIJtmQlixcnLQ6I2bVcXLM2gkwtCRRHJzLGNRBwXr0UIqDY07APkYhG2yo6E4Xecw8sv0m1wPyiZJl1DRB4vyPzIu9EauDJzOSR5hxBn+i13DHxA5fNdh8PhHR9eWUbGaEx3ikjwzZ+IWh9B9vGPSjm9nJj9iWpp5w7nEPwN6O8SRXMJmiPgFJszZIfXrjLL2cndYQQKtSrsQlMe0Q==,iv:OB74qr4z2wX/Qgq/bGIscO1l6UeR4ob/tmb8AtTpXMk=,tag:j/y/+NKMyd7cgDCcqhAgmg==,type:str]
    known_hosts: ENC[AES256_GCM,data:9TdlbjGFB8RwRsYhkyptws5TqsKtv+3qGGs24o3ptnlEYv95tzfjBwwUjPHaBxRbGg9z25MjOBIT9VobrDJUVbQzTQwTfdDPpZxQtDhDU8Ad0kB7f51hmcwTixOKi/+i9qWMiXal+DA76n8cHSSv93Uy/EwIS/gloklbFA1gVyITw9Xnvn+GPIwSsZ48PFMroRNV9LhD0uphdNcsNS4EFmpSrWqQH47Dock+,iv:nIoHq7OdA4JFj3MZSP8xH4JeGTifUiEBAGyWyFfGh1I=,tag:V5HD1yVy1LXxIQcTUfGYTA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bHhiR2hOVGFSWHBxSHFX
            enp0N3ZXS3lFY0lrdytNTW0rczRqaG5mT0RzCmhVWGsyRy9CUUdmNVUrd3N1Qndu
            WWE1Tjg0WFJnd2dHY00xSG5nM3pWUTAKLS0tIE14YWNaSjdFdkNGTmJRL0EwQmNz
            RVJvRFR5Zk1tdUkxZmE4bEhZUEZNTk0KPTONHo+p7DOd7aRnCifxDzme+mtU8IyR
            3zKnEoFtObKaHMDMIMq/2qiLiv5GV8/2IMlo0EfbLXIq1T1cdtElwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T07:51:31Z"
    mac: ENC[AES256_GCM,data:VoM0clhyX7f6UDg6OXh25eBJ7C4wPo8Ko3fxyVGX2GS58s1xgJtWJulQj/D8wIl1iIw96yJebaU2QBx3bjUek6EgArMNl5+B1VxCJnpQxQfitG+V/I690cEpayoakf2NTJRrAx2nSm6LH6i6HcKzoclW1fndasebYq4uei+ntTM=,iv:hQVQ91AoXBwbFJqUKBJF0lwm9WOpvItmIghZKLJOJcA=,tag:wbE0d/ERqE/OfhCiLoIdLQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
