apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jiqW3gacZmPpdt2cMQ6fE+7q3rSOfLSPzI/lvJUR22GzoH1ZI7+YLMPMRG9ipykHf/wh2dk81qVoS62YuX/c2yt8ZArI/NJv650ILekrv9drQcBJNWUBjWRZYHuXhqe1oFRL/zK1V1xKAJRuKk+DYO1eEkXKFExna4pw3+CXrHjYW68qcfsTxDwC7p9fAu1NMp+B98Y5Y6F0e9yDUVmrZJ5ncSBG0J1WsGT1VtlxZGiTkAlOXjVCgSHjdLSrdgjmgf+Mboliwnm1Nv/jb9TlPBygReOVfTr4CdD7R6QddFOqte+98zoJb1wJ3CRkvCH2om3TeCtal/4ji3WznIYgSW5QEbLwKzu9Ta6gsmuZ5rf05NbQiQHLiaiJ5dY7acjm,iv:X3dq3PUAR9pCfb02ffBmTmaBw+nu6rT6x16oM4WCrcQ=,tag:6s8vZ1xzOMQ1EYxp9atVfw==,type:str]
    identity.pub: ENC[AES256_GCM,data:SpeqW5Zu6fFSGk+1UdxKSC3JlZIPRi7X8qP6bILCuNhrpMWWiGg1wjB/H/C7/L5F9f5GuWkgH+VG1YGlSxNk8D799ZW0ulkCT8+44omlHlEAXJTr2GvlyRx2AVX4SBIAAPvo86jLoaELD8sFlGCgtu7Wu11E/tdmOPCjwiv1lL1IFagyhvytBHH1UNdCZf9lak9d9nznQmeAYMHwbS/XeJGT0AeEUXUkKs5yAGu206DHUIS1n7UhNGjc9RuFRLGfWyk3PBd4aha+B0+u+w==,iv:vK20UCFTySt7SKaP2W2tFZ2W2VmgLmLBdoBlz2wOqgo=,tag:/wQdiEpqbsy8mdas4aNrlA==,type:str]
    known_hosts: ENC[AES256_GCM,data:BA0ExW3OJeBXpd2FpyS6c/ITUz1TZDvWFLCFGPWa/pQMxzCIjzCL6kV194gNP0W0j3sCZ/IEO9IRadQ1KQrpz4s7ClLw5IkItZHWYeu7Mra8ibpUn6A2NjgFLaUymXVWDRQw1iQef+eSE+f16mxQH5uvKsZNzSMBu/Jy+sK+UjwZJJcCQmVIj7MzEprFmT99GFBpRBzSG/XnFmxuIcXbpsQdYAK18dIPOSKt,iv:fOAhRUM0gwMb9xbW0ACg3furtVLN/ItYjIontmQexMs=,tag:kZNlNIg+r6oLHQL9BjcuwQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOXVGNWM4TDAwVDBtSzhM
            QktVUjY2SU1kWW9JY3lKVmszK0Nub2dhRHp3CnA3RnRMZjVMdER4TTJaaHNLd3VH
            NWQ5Ujd4M2VGQ1Q5TUxvVkZwSkFNU1EKLS0tIGJ2eFdpeGFuRXk4RURlczZLSkFy
            N2lMSEhUN2FHTW9aV1gzbzQ2V1E1NjgKOOE3n9gn7NHlwdlrFWbqB66rsSo/kjXT
            ENHfEN4N+LrUSuNCjz9o5gC2i0u2OKKDTCOGQTK4VzfQr63STbjRJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T12:46:46Z"
    mac: ENC[AES256_GCM,data:T8t/VBYybM86ljDiKWqYUy3iUtbI+CVlQNsAqXF4M+leTaEBj/8qFFso/NZX+A/aagSFXThiNNc4ujbdLANtP+S4/DiU71Ov9UOigO13fvRNYyVtTmiN1XrCMuArTcih+Mc6g1raSS5lDYepc4KTvRJg+dcASvt7D07FhFpPEgM=,iv:TWZYfKsftb1badEI+5cqxJOnodrFxiSTE2qR4Rcfl7I=,tag:peWkcHtmN3FZtP0oJuTl/A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
