apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Q/a9D8WD7kEJLSUASZcedzyPkGvuGbaqgtbYEoARUj/I42ivTN7ztl4yxoii8pi7pnlYoccvW1IbhGRZDHgxt1YHLtjfpDAlpzB+OdCUcsxaVrE+YEEI4/KyAKljijjJqQ+Q2mGo9XMqCUDeWSkuwUFFNPjGI2UZpsVs1TGo/bWh0JhUoYZ9ATGbyTL0E8WqvS9lmf41JCzwc9S6d0Zk1upmXsoXNKU5qbKDvikbG8PN8MHMqYLSvIWVGnCbO0Tkzusp0UQyxe/Mk//fkoPN3ATVFiKsQdIMqqphnBPeiV9/nxwKsno6I2DNTJ7AT4bfyE5InNhJ767IPmfXevdLVyGfiPUK7A8ThsFV+3ZBFDlxu8OTI9sEvl6PMgE7lXp5,iv:dB/xnsy313QX7dj5UDCZ92lGu4jeDh9zvF/fm0QP0WA=,tag:1YyuUZdLgSp4gdJaodsfCQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:oDdlIOeaezF4xMslWG918nnYJedDCD9hOtG5SET4bO63sQxxOnwaQc9E5UHLtdhyW1pI2dSA9r574J5dkbigOMTQp226638K0vTdXbL5N75y0GLmWemKZ1RPIpAPMQrtK//Gmw7EEMVvitiPwFG+txIfyN0mCE+knlTQ5AKAvA0PGd/Qa2H0/rxpaUOgNa9k2DEjXpqweJzOXM7vbINdfdUb9/MBCto0qY4VjQVEHR3+CFDtRX7MdQrfreZEw/zoYEe66KxFM1H96W30Iw==,iv:Rx9XKtBJfU3tbwdm9gnxiVNSoCYja/pS9mk3fTMcL+o=,tag:dTcCR29k2tkCAAD+jURCAw==,type:str]
    known_hosts: ENC[AES256_GCM,data:L1YkctU010VSZZiNZCXcIa17Vv1kU7JJ72hAjaPCHaDuLzAA70BOh2KO4mGOy87uyFZ4mOc3mKsWv8yRCnxN28vasoXrWdIxUR8PNJjSL+stiaLVIMMYGNfhrn5Orus2PmDyW2Yj5iKvuSZ5RjEx9jdMHlqIo9rGL4PeeNl6s38AWwP5rcFtL/Hkb4+5rdEceXAwelO1bi6NdWbVeQxOF2W0gnQUzRIIcKHn,iv:4OTl2G1QE1oGDZK03iLDCBWpgX52ujEkOPEDq2GuQck=,tag:xFkqast/Xy6IJnXMO45vrw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObGNKa0tCNzFicTQ0WG5i
            Y3hJL2VFbXJWdjBKbnR4QkVCblpWZlhsa2w0ClZUci9IZUZ3TjFxY2M3cTVQQko4
            QVJjcEtDVmd0RGxnZ1ZZM3hHV2gvZ2cKLS0tICt2RmlwdC8weXJudmE2b2JCekRj
            YkVzMFVITmJ3WHVJNEh2by9MVGEzbWsKgKHhCI5DlwbDkNdf3bGco1v4idjwRryR
            dHX/1mKr+iXkeVF3zAKOl5hXAT4ikgRkC9dh5TPE4XupqFPL6n3fzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T22:33:50Z"
    mac: ENC[AES256_GCM,data:FMRqTnjdq4fzlTBz+yjsuSpHhB+6bLxxnzt/MgD5btto98Nbkrk1kvr0G4ZwnVY/4OEV3OFUr27qGcvqOPWEUP8xxdtCSDIZoIsLy3rvNTr1zcYqlEJVmLh0dZbBM1gmG2A+18zLAiRZzVBqgiX8FOQSmJ6qxVbGgOANi48YRHc=,iv:0j8+IZsUBL4+qaMSEDL0EZ7/N/U/41ATAXzVXihXj5E=,tag:Ym8uP77wco3BSl8pJiKqdA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
