apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jh9b+l98zrAqHseMTvxtWzrMc3nc5bjHgSws3Oz7nDUS66g80EPLXThvqy6AYdWR329NImcEzFDRPXXhh7Jp4ltaFismeXaCTiAubsaiZSR1sW0D+p8XEkMg4W8rDSY9EotqvmYtgC9LezgoQqanWasv/lV7QG9eDlgihybpy+ZSoCJHcF87xiQ9LeleuZfOgLv82csfNMxfaiss8o9bnn50W0gxkmhZq/BdIGWmXbu4hy/yMWHNujuMBmwtwi/9bmWbCny5p/cHRckW08IzlydZJIBzMQAXjt5salU78xLQWFc/CoXEkKf3WEgabU87wb6zyxWxolpJ0EWlMMihpSyy+h59A0+XhCQZvHyXd7atIFZoDBhsBCaqRf+DDphv,iv:Yttl0s5c51k6ANN09WfN3QsMlF4uIv0ap5DkCeMJwh4=,tag:9Pd+FdMemcBznweQFBxhwQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:GWtoDPCWhlE06coZE5iBtbVr+tNbnEuuGOvkRyIPRDBKLZHIh4pEiE5uWIw/cEo4sPRVrvyCOv51jl7n9IhNegceoGITvzOo2UHLlJEugVQyruIPs2wiKaeDEK81nbgQKL07aD32luGb2DGTX6zBp3sw+cHa440rItbSlGXeTv7cI8ApM0aP4wCOQLaLCCRHSCbu0WXb9ZQggz2fdaoWF8KIDscTHbuWxzM43+IKqenWVzOW0DSOaVQ4XA0i0vLf/Ms3sNPSmMC0nGZVeA==,iv:t37vXAMmkVDMFUUlTLcrHGGKD+1Jm3b3qls+NSUr8yM=,tag:smoDgTIav2yEIVdQmnsKDQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:dhv88hFkJjHFqfN1H67i34QlbI/aMFn6aol/zSQ6Ab7zdC/dhFWlnFkyROXjiDzw+EQiPBTb54Yu8ZnKAkTRycGKLcRjlGH2/F8wt24IskQIksBEuiitYc/URmQI8r5GGpYleqO2GksABrYaJB9QpyalLrJ+ggRYrdD2TEp6y9iW5U6wY0aZmBb/tiNfxvaZpyRQoPgP9m+gGpTK5rAYDdW8c0d43WSOwzQU,iv:axNx99mNOBjPjmKgcvksIgBRTz7qOqaizzdJDwmNbj4=,tag:Cvxob5aFzSOu7O2S+z2Rcg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaUZVc1R3U2d2alBYUjBX
            ME9iUnNicmpock5kcW5CaUk3WkZMKzlJY1RJCi9tdXhzczdBOE1VYm1ReThEcXV1
            OWVTRFVZSFRuZ0dCZGJ5T01GTnJEMlkKLS0tIFNxVWo4L2s3MmtqRGlUVEgxaFhH
            OVFUT08wYkJ2VnpKZUhtU0tHV2N5RmcKw4ypb1jPIgEkNPr+LkACDGRgdruIF6s5
            aQt1oHgicnVw7V3UaU718pB9oRDg28TYltG7296bN8lvaL1quODhyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T09:19:34Z"
    mac: ENC[AES256_GCM,data:7hoaXRsAbNNmrGZvhJ2xinfKI9aChP0Eelsj7+V+r5eMNnOHfALwCSR1dYVxq/UNvYJV6mp60s7Wb8OybccHIbaVnWToBIBwSyypk+PBFRM56wu7Pqc0QE/k0FBHs9mqdqVioD06g1HYLd+4oGxuStoPf/gElgSrzrstCUV5F14=,iv:In5T9cbW1W5OfsLKV0HpDg/9mtZ/9YNk28+dxKfVUBU=,tag:OUIgbkD3dxJxBaJRXRddzw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
