apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:M4YH4kTXSm3JtXIYT0rX/CbHr/Ko4zs8pioSyV+ZYneL1TKKMvc4XihdS4Bnu1rVVDEXiAx3Ww04kPANidhoMG2/pLMIQyhex6w+CDWTZ7mqw3zwa2ekJ89mHWqyPeJ8F/1hxZLpWsq1q2m7PuRWdU59hTMssY6O8LfWnIZxM8jDT9XDpFolImLAoHI0/GpbbDoQdqtjrjYIa+Y3TSBvPoeFh/DcJCm3TxeoQnwm+5CUaDGMEWk1fPELucAL9CuuE3BmmxV3n9ASfOp2RVbo3SdYzyFZiHfuJu27pnc6+pr5f0yomZ/X3CJ9P57NujIQY36mBn7PswFq1x3ZjcSEB/ANZY7FfdWXxH5KmVCrqRlK5OkX8uNO669wOONBF522,iv:B+4WXPmZK5Xtnt8K606iZ78KLzy7wDNn4+f8ZdKZrHw=,tag:wiTxxBT+vLHGVif4oDSBwQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:CYgMVHa37kF62unkc8wbYJ/ypslFbRd7FhR+MahiQvBIwQ9ABdjXmSZxheImYbs/Xc9tdagKBPe4N06TFkgfbbQ6YtAwwjmuMJ0j8LNoYeKUNnSNj0W/EVBmSE/A30ZHswG4mmrqfGaoOuYo3ZdGQ0GEK0Mk+ql31e1DVjlw3c0IsAzGzy4/9tcp55fTOgIUP5XyIw6wHhpJJZ8TLqMZzDTiFsOS2PHr5uxUY0mVL7K4NNb5sJ/4bZ2nQHxJc1WX2gK1VFRYu3Z/Uey7Lg==,iv:bnx7T/z0lQBAiwEZDn8kzvKWkLeUDrcMo81pHy/m8ZI=,tag:mbOqxVdHAUOw9lpal4hVcg==,type:str]
    known_hosts: ENC[AES256_GCM,data:OIxysaTCxr726MaGrAgnMYibq2v796oipjtm5jO5CaGR+SeXJbIBT9eZH6y7PLJRcsDwty9KXJoW0HN3Mc75yg3s0757YXICC2loyxWCKGUEcTTaeLY5n004oVTx0YBI7lcNkbYS+BLGeM+KNJlUtP6aL6FzIGt9xQuBK9irMBe1PprkqgPrLResCmt9fpV0xVhuQIDIW9SBmoaEIyew5hA659t0+e1FW6Go,iv:DcuZPahkVnR6NHR6TUZ4n7lVF7Cyu3nImED8PWs8pfQ=,tag:v5FpjUtIMQjR1WJJrpHDdw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOUlneURpOXRCUGpHWHdD
            em9hcHlBYnYxb2JIUEc4TXJqMWl6WEtNZFhnCnFNdC9ZcXJ2cDJ2d0IxZ0MzOHBY
            cUc1R2dqazBEK2grbFJ0MVVkaWw1RDQKLS0tIFpBZ1FiSXVtQlByS21TODBaSW5z
            M3gwbCtENHdVcUJFUGJsdkVUOW5hNEUKk/0PypuRFleNAGlnaCLYPcE7N1sBp3Wz
            Ey4+GVkGqKwoD7IJ5FL9XsNSryPIjDqI4uvtYB1JU8AJotwyRZ8zpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T09:17:43Z"
    mac: ENC[AES256_GCM,data:Wu9c/VRBLLfImH/CafOrsF7u1zX6izpM1brcW3RTMWiwlLo0ELa1E+/H1A2k3clr7vv7iIduOYmvU8SeL9huYSaDDZ5bMnCl2g9qeHYCXSXvs8bawtI5YnDVcydlk6VgBmipDP8LN0+uXe7zMsU/v+E5bW5rb5h/m/W4x4STGC8=,iv:Xo4WyML6PWwAq0sscZiekJ6d3cxOURtTHHPWr4P7wto=,tag:FkslQGB8y0oIqeM/aAmQCg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
