apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gG9FTSwswezrtNxtubvIFh7EOU3Tf4xxWzTW6u3cnzqUQ78dg6inEexQx8shxBAPdTi/aok12qd2FMQzkhK3DCwieJTTHsiqwweqmz+DcMFJPX+n473QkSMJheFxpiYst904JoYpgTXfuGvAwoqlPECF2hKvPdViwwqc1Cm7H0VDz/7dHy89evhI0Qhxs4gk3vmejd/VuKWqpTYis8j/EzljDZ3qbB78GJOW7X2X380sHrmGi8fXMiFvRkmcqemqZjYCnwnvqihxR1A3/4bDDNEvoaOpMxM0u6t1uKhZL8RcwQM98oCwSZDBUP5YmwNhWN/ar68BSr8lPBr9Hfx3r+w30xJkzcEx4Co7GXXXC3+EZIE8S2hQjE5wboRIL9s1,iv:LdzeprK69XPQuwEBo3T53B7iWvDB0jTuUQI7Zfzm08o=,tag:aCL+vSE4Ohjk62+a9H8YPw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZpDWhFn7KhwhI/zliurMlf6Khg0dk3nUNXj9gMHShlc1UKAk6mFrECWNpGgERqYrtmnoBl8OQemCFhOhFgrn8d0qtQpH7OLbkQbufmmiKezzCoAyN1vCiIgh8Sv/ZCZ7uXico1C/t2+SLfKLgiDLo6n/FB9PDqcXnHUtEW77VaOnswC/AMJYz/qZZBbXbmWAWrpRqltNyie+tKgqb+UPQ6RAbihDpdnprlmlhDkaED/bxunrhfTAbSaCZwPldWiOgiFBqhhO8HbiqKg69w==,iv:lNi5tM5WT2pYqxOxkWc4ArbKyAfT9MfXd+197vRCU5g=,tag:ynkMiMUqn9xRqA440kTQ1g==,type:str]
    known_hosts: ENC[AES256_GCM,data:cceDcw+k4TiXAFXMtI1wrVcS1YeY9QXVu/cJO2yV7OhXTMByIMNybjY490NK8iit3dr6dc6x9VRb1QPUxwB8UPdcWpVUh/nqvuPzbCq84e63Dcb/BqxvSzs0HMJ3WEvG+hQTrAM+QJZ4QQTPfOm5Qvc/CvEgMgqAIQbnw4R8d+wcghtBkb1mvL9ePTRxAxJ4myskOtk9XO7ijB/4GQMKGOHY/Ey0IAq86T71,iv:UOukv1yIF1d1d87+CXKtgpvOBoQQWm8CJeEbCy+5R84=,tag:xoe2O6W/gPRB830NCQmu7g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWk5jYk0zL2d3R2NveDBK
            YlBiNnFxM2lFSnJwMitHbFBEZEllNW56d1c0ClBlVE9FSFZHeFRKMFpQRjBnbTV6
            akx6cUMvdURZY3RVNVpQRXhuVGJSUWcKLS0tIFpRbFZ0NSs5TDlsdlQzMkVSUXlH
            U0hIN1RXaE1naG1JUU5yS2xHQzBhdVUKqEul2niLfWaRJYUhBpjCHmY8Lm/45iCu
            gTcYbmHyKBD+ZsV/IBbZilyqyQm8hbtp8UrGVDhuyv1mt0mJg393ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T11:27:00Z"
    mac: ENC[AES256_GCM,data:q5qbEEVTZ7uLyOTj40M5ZaYFNmsSMeqf6YVnwLvQO5Wao8EyrJSttK5cYNCZnwYR7NG3+5eTXbEI12vXxpTFc+as3ypKNifFila39e1Zaiy1u7i/QGWR6VKQeCp1xyrnAbvHu/UEgFNr3xCj07jJGovA+f04/hwppIkeQayV16I=,iv:LrsMhSjFCXXAekbXixQLrunfHphEqXubVVnb8p1/BvY=,tag:yqfl8YcnSoGMZTMHrgQOEg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
