apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zHb5hrepy2S9l1D3TXtvoScCyRtcqXvwHztiKr/9nHJ1v8BTSTN8bsB5dFrX3dAvsdhCmStFrIHNYBnBKTVJx/oB4gamfbqbXNZuYeWP2J87W4l70+waoLqgDCwDWZbTf1UHn7/5dM/0+hTBKT3nGczBTBphxaJ2dG8jKj9xpVbis5CQWPjawUPfqIwgmgmzLE5WB3HaH2y+DiQS6oQmyOPOaZ6GZcVd1zn8NVHfsOIjg5YLAQE5ZMAzXahm1UzDm6f608c0IG8J8ys1ry4ANue0p+rmw0kcN7DP67Tgm+8Vb/nHpVzMgzCS2h5kSNxmq43AaiRTAf/brvytCbWy245ZOE688Z0+QFQAtjEomRg1/A3mjaabScACJ1qRozu9,iv:vys0xQW/C9pBi5/+MNfRhcmL9DSiOIRsIaU7A6MyQj4=,tag:gcQ4c8XN45zjg71gZaONYg==,type:str]
    identity.pub: ENC[AES256_GCM,data:6fOXK4nc53/LbLTyFh9SVkoe0Zlvn6Q0ZsWMVbT3ovTaxIiulgnssLJWqh0DwwyThcZ1gKFqZvHSnjOV6IvrJK8+OMmbod+QMBKSra+4p4tRuqkgvNtYZvaxRdrf+VgvYFHY3H0O6cfmwOQVFaWGbyOOJwzwvZLcJXqas4uNvm78dY0iqwJoCkIOzmG0jA0ALiCBnsc6zSoGP2Arg6UncQbAx0Fdn+ICpT6MOw172Gr2XVZwoAn0U4YTG9Cw8/L3471cwfdyBSmm1Q64gA==,iv:sHsuLRCOTxnkZB4BxYPFAmdMq/s4nRQLlZzX7w/HmJM=,tag:AbC3s26xPClMZ4w2edxNFQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:dLHjcGrMGhi2Y3uwUezXwmvWfGWR38NeArJ86K4lONpFGUxztnoEkz+uJAVyBMbUzmngsLHvWEfT+glUVL/eJJfa2pRx5mkm3XIyk8vt0ypOmDw3j3VUttBR03CAXpksOsJDe3KV72HF1A6pIvDhMXsegf4JRQkbJGNr9ZJ1xnPz+F5VjrQ/nKmMiiCEthz73VP2mNn9iwGBkXI/hxo1umYmFABcfqgIhXhV,iv:MdWUWIw5G+d6KxHCl1NFvYAhSqd6k+dvSjarfQ6xDmU=,tag:mjAtKsgwjLWJAnCS9Y38tA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITG00OXhwcEJpejhwOTJu
            VExCa1F2VytjY1NVVEpqWXBtUW5zd2UvMWxZCjBDQlZ3QlVuWGhVU1htWHJML3Zl
            OEVMTWc1KzVqSzBNcUo4cW5veUhvcGMKLS0tIERKelVYUm9xUk0rdnFGbXoyNlNw
            MUJYNmdwZ1p6d2ZyalhmNFpQYlU1a1EKUucctItJMdYpMzQQ37TUX4f2fWnGwH6z
            2vZ2v021Re1cD3Y+cYZS0MQsalrjCcYYQH6GOhVAaa36Dcw7+drFtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T08:12:22Z"
    mac: ENC[AES256_GCM,data:a/17gLgBOC8Cj4z22MHsR/s5SlpaGCC9SQakHnVXwiCxuIRPceUIzpHQ7XT1ZpuyE/W/wEjeQP0I+cHwKu9sdyS6dmmePhWIeJXNaHBST4okkh5ctwdJF02Cvp3WaliB8AIBuhrLGJGc9NdBvASAFiDHp9tEPMbdvoHGn4p9Fqs=,iv:Kj2dvMHqk5s/lSmiXl9/a9jNVqC/ujxM9ZQQmmxF1v0=,tag:7LLQi28+XQh8ALSFpJkKzg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
