apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:V5wz7fmEarxcq0/P6cPwsOEm9sHdzpjINfBfFjea7LXf4dB3vgJzpbfiOuh6mRsk2ebpMJjwZU6OO/pflNGiG44OHu8Bc+MRRnLgYKKyIgniTT3zEOTW9oI2Cx6VCr1mk038jQPQo1A5cpAdvJtOQWSk4Wk6MAxQ/vjqPKswb9K1uWh6mYYPVxz5aGiUUREjTy52YZgUK3xNqHpUhXxhGswld5i305QYDwHc3HMzkYxA3LAp+hnCD9LEzWOktzf89/wr4nwU2nacy3/rc4Wku8nUV9GplfIbcfj3zfiMn0/mPp15jOQE95twxHStKcuEslLBjL5lYW9j9SIHdgYFFAT2FSz3vMmZvJ5+nzXnzTw5qgDg5VkdEhFAqvfWEfzq,iv:UjEYBh7aHOgSW2NkRSaMbE7JNjiTRUfnQtJ8rsVDDsc=,tag:qIUWaVR1mnvsiHR807xhFQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:f3K09IVEo/horDqHHYjMHeSTfU3FPManRus9VkWh33Uh0T2Pj5ADjA0QRlXvAtmnGpKZ5i/GWG80x+i9pY7CgR4N4r8bGpeEvL/YljsyD58VtFPfWd0PUdcnNE/36MK1rKms9N69nTdmoPTDJje8T3W1hBNTM/OBhjvJPAFOr9Xcr0KgPLWuouEXJ8l26SO0WBxJJzB6PyqXQqBe0XNyFQ6nN3LOJ/KaC+Z+cP/5VOolBA+yyxkLA+3HZSNBarhDp2yCIEn1KSe88pqzpA==,iv:AaIRw34P7UVXLgL28hXQEedWG6MwYGQXAFJ727D8WKs=,tag:7/su5QYyGcTiI5Zcs6QEGA==,type:str]
    known_hosts: ENC[AES256_GCM,data:5TJuGRxP1nw/LuwxzNSut6pakSEM9mEkM1D8uwHLy5jDjUOlxNj4GaaOKtC7ncGD5PojAICAc3WfmLAgsdGnhgbfCml4T5ml2b/D++dzxfiNmy585LeRbCTestGZZ7H47sOihcISLQ5p5N72pI8hoCEYuFLSTN0Rroc5M5KuzSIeVoL3kJm4qNuUavcit0lGbVZp30Wrlyf5uzjQS0HtSm3SlK2MinfGp5Da,iv:dgcYAtd/YPee3yQ06lhtm6IXz5DmsJRZPyh/njZZWL8=,tag:6pgBtjsomvYN0/HrMIbebg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUzJ6aDljbWJ6K0ZmOVFC
            K2VkVTVsdWVtUzRiRGEzZmFIckppbldpY0dRCm9xbXhoRUtoTUdPekoxaEFPN3Jo
            bDl2cnlKUUVWUHl4YVgrcHowWG8wMGMKLS0tIGJieDVHZHNETXN1aDE0Z2FNYW9l
            UFUxNmtBSE5zY09lTEk1eDBtMzVHWE0KiL4RoSCtfLZR4cq0cup4jFCQrCgFA+jU
            HtdhrTAgFz03NukVxvuyoXJha5/uFvNsuMbL9L/h426Eh4DLupOwOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T13:49:32Z"
    mac: ENC[AES256_GCM,data:o/8gxdR92wHcqCTcavKcvaqua/ejCZMxzPPGcMA/KrjtRh3T3GA2JUY5AlBjhwz4W7dzY4yuIki5PSDwGugmpuMdjlLgIJs3Y/0IJu7HjKx7Kc1U8qxmFu/SGct1d1vavYTW+ZZf8mAhU2RfwOMPDoUvpJ0S3uSkAASn6bVxELQ=,iv:dr0Mv55Mqn/KmbyJSPcZP9z1Af7JNNIg+dTv4TGU7y4=,tag:P8mMg/KK8ozj4pJFkjCaSA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
