apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zp71VGBxi3TYnamemNYERzHKejQcmXaUhsh7Rf72Ve4EhFRwoiFHgKUrxJdf0uEd/2tFhG0BS3A9qF4WvtZCVQ4+u4TsTwsSR/korKm7LOdBhaeI0okHfVWllaDEO9WLNB23q9QvNzZ0/Z52YkOFQUKRBWZvRBhH5YoN3Wzh/o/aJu6jaZcU9h9RB82JYohBnIt6vYiG+VFzwNPaGWV8R1q1iVz62dochW9pU4MXU++HPKc4MEWZyJJI0pxCNj0FCckmQjG2hm0LXJ9Q3oIkYCHFgq6zqq4t6CJ6Pt8fJ85m0ieexOJyO7f4uK/pdpZ+nzVHoCnFoXIhyiXYjIqjyrlTCI00B4r8jSuWSi8RqD1hETgw7ODnPiL54MuBwoG/,iv:GF1SZa4RRoXsJVJezXjg3spHo5NfDbhgd3IIADhYEdc=,tag:bjC3g7YrO+9jtJQD5MMnTA==,type:str]
    identity.pub: ENC[AES256_GCM,data:vATtOhV+FTDmVaVobcSVcEo0pfARW55iks92KBklx1HP63diMTE/rCkinLUpU2dbb2V2/5GWDttTNFkMj/G7zys56J7CyYsb/aApM1ywp1Q8oWFHOBhv53lQIk9DlMCjWs5VBUim5sSOpgR8O4VtDWa/bOghCpEQQCyX+ELXBXHoeB2c+SDE8m58/c/REWnyQ5muX7/S1qrt7A899VWNbyC6AGtDmpSTe9f6JkltOjpV+xZ3fjBQskyCg8aYMzBJzSht0zhsaHnThEK4iQ==,iv:bS5wIpWYhZ3e2mO7gQ9uxmjxt2wtamd6ZQIaGnLzOY4=,tag:s7p5GwQ8GlmBvf03lZOqiw==,type:str]
    known_hosts: ENC[AES256_GCM,data:BhZaB7HlEKfsxk/J5TbZ2aP4VuUUNUKj9piDmC5n4zc9gHPzaRKC0uKo5/cyaZowyaMlLclD5R7t/TdBgZK1iNBmGOveshquoG+QHv9CDOhWTMcj4/MLdakGO3GyShtkNu+LYnV2poyQRrNyVFjuqHLJ4rF+gKmhTfs44pK8SUFOzzhZkUw1PheTKXp1swmFSsRQp8XO4pL+Mht2lAQqY68vU4SZDaiqIFqw,iv:2oqW1pwY7Q+TgU3TSMpsmwpwQgwxdNi8T0U7fs0TrGk=,tag:EyhPvRhBw82Qy9KQyfuOKQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQXg5QlVrTXZFSGM3N25i
            TTRwZmI5Y3haaXhZUDZVQ2JtOHRPdTMvZmhVClhOYTZ1NDhNQTFjZ1dFRzE4eXlv
            QzlURjBJdFl6NEpPODZINDY2R0ZHWWcKLS0tIDZ5MU12cWpaMVViTGkzV2pWQXJj
            dmFqZVA4enRmbzEvSjhuQllibWIyc3cKCcNV1bkaBG//5HCvc/PPpn0CaekHrpaV
            wqz7lMktKwbhlNqoOkwq+GkwbyOJSFvfA+woS3LJ3yjqRp5TRlHIrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T12:29:01Z"
    mac: ENC[AES256_GCM,data:32pKkpJwD9QxL97Gf9HlQKit752WxEz+LMfw1qz3/9gzBVwwLaNCj9sPkspXRxoTZFlDvzaofnBBpcPWMJ7wdbtY0YCCTo5WobGD6LxxAuEqMyoetc3dqIHp5spzmyUu71jE56zvKoTzF29WOZLAnLwhQMzCVLL4RFqgqo9JsR8=,iv:7nto8QsC3zt58WPpwK6aoB313Tsjv+ovEQF4AXYoxlI=,tag:DMcrwgs+92otUZiLk7dQmw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
