apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UsKhz6Q53zJNIkNbEt/SFkgRdlO3JQh5nMMYLBmCvTnlQh/FOigPnbAPn3zhLeeUMwjjoNpjJ3cTpPOwTgBKf42KXa8/6GynsJRQZefjU3aREzjukEN0zE4i5e017k5casphkNohFr/PUKFxLrO5s6quu/TcR48axUwkDS7mye8defEIEeaLh8CiHrxeGBivrgcvWIJDOSQYSED6WCYY4vJM+b9v9Sf1GQusJSvCdcRFvjg+ktCfiCyhCqXWRLerYL0x9ajxoOocWG/89oAhikxeEca/uh+biuH7u/1uuhMyOFljuUip4CdxFuNtTXK9i67aohwJMEbw4urIc/nnGVO+7cetmlbNuqO8pF2Dw65lKANStMo3oB9NFBad+z6Z,iv:Hm+92O+pG07JDROX6jt2KCN3ws3Bxmnqs47Li5juHlA=,tag:ghYJUGmDBhrqCApyOBYjzw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Sw3ypV9j96jpbwMFWQfCxphzhGV5mf7aqFZLn8x5I4XAHXYjSIijzWk4HfdRyli9HzFJvEmkryJQD2w69ama3p1nye2iZx4k3U6k2kTM7cGGhXe+3sIe0Qpqsu3DGOxECx9Gkkk3KSM65UaYadnLr/V9/ldRBnXELeNnC2JagZ4sku/jHb5k61pm7PRex3PAHantekFEBWutrFiNoKHTU7h+nK+FUfGdOmbbCAdgo5oM2kf046tLbvG0ntwYqDgTMPoQ85aHX7veBXAOPg==,iv:R4StX5Kh/0bBZlH14RHSph5qLqXOvUfu0Tb28HojhRA=,tag:/z96GlB5eBM3bNJWMFHHgg==,type:str]
    known_hosts: ENC[AES256_GCM,data:A0rc6V6++PTsFo841NIeLFhRfUtTM2GmwcCpfTKzUkE10VU2fhOnKGA8HVZ1KES/xPxG9HD80vQkk2fAQ4qherHzSb31tLE0v2iN41aYWu/lLOyVqonFBsT8liwIDVmyYdxW+6Ie9MVLqh3Yt+KfrGvx/s3tZev2LCOWWl/uXjDnajL4ZgpYHGipnOX+osGrKEkFS2/ILmQ2Tf7TMQ1GyI8FtLXfSwHhrlrx,iv:00GGrVmH3r38/Osu9CLhi0Fi6Iyg03zze7Zz6v7fwkk=,tag:JOHcwz6vcXtI826NfVPaWg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraWJHYk9GcEtUVGpxamlh
            clFmb2FyaHpDVjhKR2RKNTZPcWRFM0J1dVFnCmo3dVljNjlmTUxCN2pxSHVKTWJD
            WjBpZGJLMVkxRkQzT0lObUNpSENKWVEKLS0tIDlyMUpCQVZ1MGhlYmJzV0dkMEpG
            SDdDUUZ3TS9nNEVqclh2STE2VVhPUFUKV70+My41b1lta0sg8++GdBZWeAZf/cEx
            ndWZz38bcduyZz7jvIrYNfX7tJCig83awzzU4jurEKonCD5hM01uIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T09:28:32Z"
    mac: ENC[AES256_GCM,data:o8RWJpWPJNLswj9aSY9vjqzbgNx8R4KUKmsyIYoWev5qVrBnMaOHpSJ/qbFBJIeznfEYloGXC/nVWrD+4r7QgL6VwsK4GD8CEaDUuqU1lO+kQT1pBNPZaTMRl92lFPKnfKtq96Dr6eIlI9GtWDDIl2hhtADMzw4o40Na/5wEQ4k=,iv:nqiGpqEmYB0Mu9dNRJ2OD2AOTlBHGKgCZHrgyozJq70=,tag:PnoGDmDkeiFpi4pwH8dKpg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
