apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:DZ3M2OcWtEw5BHDZ2QW3uGQZw/uXb4ZGeW62NUtdFbd78WpCkDyICYeeHjIV8RJTCm7NBe+q98wuCrOOIVUMmIOTg6Nyuu+JDz75jE97RkA1aSthBh94tYAj4WxCezDhCEddvjqeM4c3PSPiFhWgMvd6BgyZXwhgjAY7i5NRoxlXbuXqwCQcDPv0MUK7rlc3/mJw9ClZinKKvSBaecNdIgk3ZntMiD4qbC5iWhmb7+8umoBYMnYo6a3/Btr8zEluVwYuDm385GQevQuR0bcLf3ao7XwgRpxKegJM8DCOcU/OpfRtd9pEawtfURRP5nQD3PWCoKBxdwF56MK+4/89Vf0fJ2u+KBqSP71XXwucd0LCdJ/92E/hYahKTpllyOIq,iv:Em7ojHXZvZM5ukrW6ONZpolUrxmErIxQXlRtO8vsukA=,tag:JW21FXNqpbRBi61l+G4bog==,type:str]
    identity.pub: ENC[AES256_GCM,data:7/kNSY+cELNdt01bMtTubAB93KAxM+FUBWU/pEEKx8mUnmfVeDuF50omjwgCUk+nIFb6fhS4/hpuYFCw60B7418p8NJkSP02oSAKgwV3bv/WYOpfVVAH85LAjyMQjgQ83ZeEBBDMQFhkatu5TuyAdQV/qdMPKauw4oX650oWDvqAgctUnqRy9V19RDpjdEgvQXYkV+INLO0n20jF2qGlViXNSWuA5s7yrVy8K7Gz190yfDrPos/6430EZ4WdYR6PydhWo4dV0JxC9G+Img==,iv:TJfQRmBXEji+7jdPz3w24Tbxp+ZNcGiV2EhEh7F/nmw=,tag:zLINqa/WPobvT7nQGhtQEQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:XA3FKQOVWvo5qD6LjF1uT3w8WmKRI9dsIfrTL9B7/jibX1+nCRW8GE0cf613Wjpdg6WWSJzVgEZuBzw5i2SGjP2HXsnGgk29TR1+XKHD98U55WcFlEBz5vt5WUvHP/cJcbEZIDAwUF/ZtOaiYJAbw6d+E9IBgbfLXByy+EIK9mmeQ/NJTFip32a1rS0ncK59wyTMrP5dG6VEiD66z17cjwGGllb9iNKZf3rc,iv:U4TcArtgmExbmkGSdhwOqmfnK9u5cfEJA6n2YBEm83I=,tag:qzWATPsuQjDuxrQ0oCABrQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NGdLcks3VHpPYlZqakU4
            bEoyVExNT0FleVZjcGl1ZzlNWXlOUGl2WFVjCjMvQmpQZVcrWk1uQ3BkQkQ2RVNx
            YnZ5ZDAyWWhPRzNTRjBMam5FMkNxdW8KLS0tIEphNG9KUzR6N0M4aFduZXN5TklM
            NXZYT2J1blNDaXdnZnNlQ2pLcnhaOW8KEB0JN+M/8l/SVL9jmr94+n02J2bTDySZ
            +GtNozd2ZZ97LC1xws5izQmPOsY3UpQ5YqP37zJkeh4BjWd/7hyeGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T07:54:19Z"
    mac: ENC[AES256_GCM,data:+bO9Nr1TLmgikK2zamboM249w8EUr/Kz8ZoO3knBaDuV0LGVLLZLOC0XafB3oGi86LkHZj+pogREQ+jtdvjQsK232IZCgNghx32qFo+SzAO+NL8eQn3u2Al/TBlt8+/rUODbZ69AtsMGdl1VAUt51F8SEM83IGan0U9lvjgCm+I=,iv:KLNxxVF2YH9kVqHTNDLyfXS9fHTAf9ISfDlEp8A1Pjs=,tag:hnxGcnzc3BypAl4cEPppZg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
