apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:or7FcpkShWvqh+RqETQOO3ijlXSxpq7x1BdTBmCxzSvEbGMwkOkBWxPaMCEzZOhlwWglBABloe14Zsim/cIvK107huIA3h3sDlpzAw+YS/92O0Zo3+XQ2Rm1IwkAzHIwS8JHOkwuLxYHFwS7iJ181X/FGH1YA8pe+dLrV5bUCv4qqiORZUV2w/vTE/vBFA+Vm/QkTrXvwbrd1R0TIZoScq6eK0UsgE2XFJaYledLGEiX+PjEZ114FllygLdZs0xOuiynRZQZjvaCdfRMxoOnzmkTFExoH7jmW/+BaDHLJ5YyeBZ4nMkJDLV+SPEmjIuJPMRC53c1cCC2cRpfktwbWeE0rdMehKSVRj8Ku8MA3qdMIlu5hppb7C4X7a2wJF3l,iv:OP4HRady8uQpBaoZRqYQAOu2lwTxQWSuDcCnuG3nD14=,tag:K0LsxE87l6kADqMDvMy9DA==,type:str]
    identity.pub: ENC[AES256_GCM,data:RiITL1cA9zej90M8SF3/rpRCPBDgmm7B/R3XPLZrakQ5hYQ/n/vu3mA6s4J6esTKe8ZupcpZ17xZKwWzHsLFXalTPsyN9UZ2cxwGfFjVTJG/hJD7FNI5FjgBMShM3cRvc8s4c8eeWI+x+ojz2z1n1wbtPkbu5A0wB7wXgUmnhTIsdqljrbky9La+IYgBxrwtX/gaJjYcEPbqhsoWme6+XNOTmsng6DcSCMXoFyPF6BxO9OF12aCErfZMyK+hhqx/Mg8zGU0AP90VqYdKMg==,iv:GmUvftVi2pH4Y7dhT+4CkOG49s49Hq4FhYodFVAIHhw=,tag:sA79ZCx+vhc9P2NUuR6zHQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Ojc1ya4pmrdRAnTqc76TWdGTDIYamkCfvJHWEKAV4cjWgNLIgKVl1L6DmRrorVYd3Gr8a6WRj6nkYjJ4apwlLijjQaRtF2+1cbtgywRydW5f1AqK5P7GMwzubUty5x/ztTpb3aVO1yzA+qzeq8Go8ZO+bkOA8sCnMNK231q5MLcRmmGp2nvvUKWg82TEpWe+TmuHmU6/mcaH2C+5yI01DQMGh3KxfDzwEeU/,iv:wcMsbDupnV1l6qptLtgYilvXl8tGC+CfigelufTUZPA=,tag:IQTT/LOJKWKlRejQHT84BQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ2tEZFh4Q1lKcGVZclFo
            c2NCS09XN0NnV2hVb3BQVk1kK1ZVUFBsdXl3CmEvazJWcmhYVXArak9McStJcy9J
            dTRDM2FMd2V3NzJ1OE9WcCtNby84WW8KLS0tIGdQVERsdjZwbmtJRGhvMDJSQm5U
            elhNSlduZWdxSGdBTWYvNHA3aHo1TGMK9CTq2pa6Wukwwr4BZOSvhr4uVYIQYh8l
            PY5nJMW8jHT/kY/SoW3ej7VD3+fv5bSTfEFKmy5b4C7fM/2smjSzoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T12:53:53Z"
    mac: ENC[AES256_GCM,data:R+rniNj4KSQH7sWiVszJpg0+TW3IfE2wik4Nm9GWvZ8ElYAG1fjd/0dyKUBvtMsIMVR41h5t1wHiSvxmnsFT2vUPZhifvhu0shsU/Cvb2eKhqIeAGJqGpCpS4+IhyssobAsmOsvnBX8osvJQWRH2SKsXryCuyoVN2ZMP1l6kxyw=,iv:VSx+4FYgJFU1ibOVon8nl/Lsg1N4ug2BYlrvDWN1VN0=,tag:EN295lMkeCAoD2V1F5po3Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
