apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IuC3nPOZFUtrBV3D3xZEj30EDw48u92NzxrKDU9O5rL3i9Qg+njM1dsscrE01+OUsGapXAkat1F5FRF5ebTwESsy3rnbP7e3SYKL46Cg7iLeorIJmlxuGNQodE/RmJFxbkKkzP43ueMWxlYsa/3TQt1FKQ7fskCHlH25BGvjz4lG/y/zD+K1mSQd/JnTsFrgrEyWWVWyMTj+WWqGQhSrqjXAvquZ499cCQtCLuZksdyxloVLbF1cUrBm+52FOm8F2aLiqcmNh/qI8YRXk7DkeaX/YH+DDXqMDPbEvug7LZoxjXNotmCffp0Wzy+r4J9HNVpECk5rkmRIzC/3L/4GoQDW8hL/wJGy8nMA+zgcCSB8xquP+MedxGXmp1mB4zry,iv:WLJhdF8UVV2TVdLnPEBOGCb3Y6YvcJbNtIYVL7CYvp8=,tag:2snyBNQ3k4yd0OCKwO1fsA==,type:str]
    identity.pub: ENC[AES256_GCM,data:gmOYshIkFa3WHhD/oKvDSZDoZDu+ZB9w/g3E4rVhUe6YgvcaeIEe8psq2fYVXwzwOeXmIGzNJdG2uB3Ysi39RhRSDATfKozT4fscX1s9b3THYjaNgaVMfpUDTRI1BRhqDgYoNZcrQfJR0n9wxz3sB967VEqIkXswswx7NDINNtZkhHaVtuSXgqMQnwJMYIbiXmL38BjPjn5M182nLWBhkXm3mAs55v5jyI6DzJq0LX7lF+BtBioBaHJT76OuIrrlrU6O6VHAUMB1hxfcTg==,iv:iXhgIsbE6iAtNEgV2A7cXqxpfc+hAVjcmbYJZ1PzVJ0=,tag:/3G32CHnugBvKaiezxyFfA==,type:str]
    known_hosts: ENC[AES256_GCM,data:JIkWufQl23Qkc+jm782lCdJqFnfYUdem3PgV3xJYGy0br4kqz3Bs3+qxN4y60f2MpnitAXX9V0hITXDinQ0SsgWlc9mI+QHv+9ltBDJmpEBdbrdZZz9gOJyaNP2Ar6CPZ4cmdnSQuKR9jffZYjjezpmutCNGuc7XBfZlGT9hShDbTeQ6I0c4dyVaqJL4BNd6WHvL0OQrRmtj68cK1LsPMj4+Up/Qam8zqmkQ,iv:o16GJVzhdQ5NNHoR2vgyE16M9YmzMy3ohXHZQJoutnw=,tag:sUcpezqdA/1uDVK6EBTOoA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMmFDVUZDNXE2WjFVYjZk
            WUxJT0dCdnZsSVo2OGpXL2NuT3FVUzNlUXl3CktIM2U3ZDZRL21jeEordXpSWUZi
            UVZhalpKeml5UHYrNVZOYnA2aDVyM28KLS0tIGlkSk5xbXlxSEFQcm1oZks2WndD
            UTJUcVY4UUNndUpkVGxMQXBkRVN6K00KYWgoj0XPLVApFpMISMxEkvbZ6PizEmWK
            QT0xghry93dJN+10bZ2Wuxk1JZ1Giobd3n5nYO/HiJsz8JKw/e8+Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T19:53:22Z"
    mac: ENC[AES256_GCM,data:f6xESzwvqfU0vmIyUdxP9DSx/6rhB3y/8IUdmcRkXhOHLvSwAxbJFeLR33ZjvDmG1gjbzZ4UGoOX67Jxxb4eyrS2zLiE/CWFJIuUaYzb8ta9l6btGykf05EOfM0sZqiZjyBwmYBduLciC7lZoNIyyESSbikKdU+/gSb9E79lnw0=,iv:NzUTPcwfN+2M5TEVz8khst946wSbq++nU52DY6RIpJI=,tag:vZvgfwVhNLHQK7c0gNTRrA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
