apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wJTqE/35Y4vHX+ySZD8ByUOypPMFYfKNJd/buUOfFbRcfMplcgQbLNJZj1o6utbx8yXhUAP/EKq0o04Oq0mLp0AjxyX5niUKbWPrEPC2SMFyWEOd8BYmboWDQvFjMKhm3ISCMs6qM8gSD58ASkFTs3Y+qXsSUMifKNYEqusocs861ftU6UtQ44M6QkMzb8ZjMwxKaSFIvgr/G/EMUFVvNTmhcKXwpyOfLiMIXmo2FAQ44tD407bTKSpSuTMwqJVNieKk3nZi28On9DnHARNl0AJjAdRH8ksdKmO/hS8f2Jt6Nzr3WbhzJ4plmsdvMHegKmqWaHv8WPqVizEjZabhqr6feRDjduok59nBUTUntEKt9yIBIFxMdLFV0DN6zk1E,iv:eJGE4flOKRpWyo9v4HwkZnjykqqdncWtxF4ek4tIAOA=,tag:9FcojTLpzPJaiESj0OKupQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:2WmpGS6pCXX2ox4KQ7LLdHZDEMLKaLrFvE7BTXIuUQN0RoPxIfdovaxlGI0yYgKe9G35AyV3v+IxirCSTqn315H3JLQvrjfSUK0qbj2aSFYshRJUoBzLn8b2CNIMD7Rj/MuZM0zdV9fT5VkfL92XWH1YuoC+MXYo5au0kO0QTaNtAoaZQEqURHpXB7ciTevkM/YeibeAeUZTqTLWpgmyc4ROYEHJPa8zSaYr7q2QUGwldyexiyiHGdfTCd8hLA1EyDk9xR12BrPudLcaLQ==,iv:fEusPpreGTRcx1XUmcb7N4+cmQbYygpDrb0engUg+lo=,tag:ms0Z7mFLU6zHn4He6pWyrg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ejZopySHM7xCacB/3DtFLptyaYHquHgZW/OEBs20PRb5GwseWAX6DEguxI1hYPcK9SI2430kBIdV9OaggYpb3/i4PQh1xoiIsQcztQZ8xUh6UmMW1jjc64bzTkjrWiJhLCF8C7hkB0bSGP4VHblU7mSZNXAUapkJOXx4B/+Rk+K6FZ+gCm4muzTpwSYp0P+yqGX7ZcwV6SOb3stN4rd2tVADarKookRSmbRg,iv:kymPwZxBn59R0G4sVOWRZBW7zKIQDoLKMBc3+Tpt2tc=,tag:f0cog/2k/r+nDPZWvhumUA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcHRMUXY0M085aVkyd2hJ
            NVpoYjdnaVloZjc4YkQzbnhQS0pzNXpFTlY4Ci90M1RlS2NYSXpzZThPZ04xcy9Y
            YndGQUVOQWJ2UnNsTmpGQ09nZDdib0kKLS0tIHhXOU5PcGdyOU0zRjV1dmFNNmda
            bGZnVGJ4YTZ4eXMxa1JBZkZmcjZuODAKvvFb44hwRAORzDXxBvbHinxTN6zUetWv
            WE2jvPxctJhHJXRaD8psjs0Wk/FOJRzwMe2/M5QtkiG3wf+RVij39g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T12:20:08Z"
    mac: ENC[AES256_GCM,data:4GgOAdxkm+Bq4SaS5IQukChMTx3eiH29hCGGDlFsBynLW8DDL3XTX6HktU3esmtvnLgpx/md/6oSsRyaZongHCWyxMZcJYkzEEBS8TC3R/2K0S5Wp4Hf6fXScOKyEVe23MgTsMZN8RCTtOCrkcEtNklE19DqSJXj/ZXpI3kHdoY=,iv:yejI4GPL4Hz74iTCF1m1MWsH96mHzLXCGjLntDbNZQ0=,tag:FqyhHUPfBCHQDIj28r1Yhg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
