apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:YdiEeJDoQy/ibx2j2jFZEJdZo6WQkz9u/uVSN1V5vsGTgUgO1PRcDHHFmdDp1qzTn8IAJd/3CXrrFVs97UhpxAghqEs7vHgL76mPUMlLAkYGqXj/def76jgOcsNlBknC4cpe8SmfP+CCsua/VfpemdKpEd2GsXgq2qZvGQPzFD6rOIcz6opr1yAfruuFQArrpS7yQuK+d1rp7+mmTOrjVbpPU1o2dcdX8EXygesTArxXV1d7Lqgr+RM4FLEExykqMEVPl1mSGlLOLaVwdttRwygaQGkdHqRHIGLxMw6Sylp8n2KJyr+s4+3FGbG8dFRKs2I66qCScnzxNyIRHD74QL/lzq97F6nfe+O4E6LxNi+ckZh97R0t5s4Z+86mHa/Y,iv:CSBirU/A+e87Io7iT/cl5tRzVF6m2bnHAuaB56IpK6I=,tag:asEXXv3ZjsvRPSmLESy+0w==,type:str]
    identity.pub: ENC[AES256_GCM,data:2doiov7TjWs+9JyKDWrjSZywCh62H7J5f9xFZha2ZUznQY+14a0jR1SeeM0bHS8XnFB2H7KnzvObkfFp2gpW57AOAy6dK/FcjXehGNI19VPsrimBkiWrUIONcGf99cUPMwoN9zCWbn0e0mSRyzjjI006meTdb1YAuTwzjHlfo2agOZPvgWRWuVJC+2sKm4bKaLJq7szXshiF1gDmuvlv3b9FSuLYT3vZoweDgxdcHR8maAGjJ2JIkBW8MoJ7IzacNNWU+IyM9X+KiVMuug==,iv:zSjaVd7oveqyztdyozM+sd2ck1Zbl8pBdGZlUJ41qRA=,tag:cGx8xqaHAKrYkX52w8EW7Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:XU8iYVsrma5RPJXOvpccDxp0fR6yRN6NPNBkcTtlouiE0cu06JOsDgVut5io0Pm8NXE4+X3KqOGn3S93q7YTgUHW3N6x2CXYSxjHvax/uaWAp8F4iN9OsqyFy3K5qC2HLnLM0PipCtisFtSOM9jduVc1U2Q4jUCPm8dlq247xTkerdPRnb9PoM3trtxq0JiHQAbGti4rDW0ldd/+WBQvGe6ht/BXEW734MvR,iv:RZXlm1+y12KXlKfiI8mx7KdC1PkGfn0H8XPFI8LnN7I=,tag:X3xGoEux6IDVZg38fvat/w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MC9sak9pWlh6a3FtMEV4
            bEUrSGFCM2hJcjhrYWh0N3dTMDJWWGFGN1UwCmZBbndTbmNIcU56OXNXZWJMUkJl
            UW5jS3diUGRLYTJXdDdmUzR0bkl2QmsKLS0tIFEwVXBOclQwem4rVENwbkhMd3dK
            ZVpLWjlLVThBNzViMkNUWS8yM25NR2sK4beePk5Y1MQLIvY8xTf3765cpVzsXoNn
            jcV8AhQ2VPAKyHSZl2xgHErvJUaZssUbc7K3N45sYnsZuuHkja2AlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T07:59:44Z"
    mac: ENC[AES256_GCM,data:o+kkyCdhROCs7hfBuVsNAYKRJyxsi4J1KFpK3tMl/ITMGCMpXEp3Nd5RzA+bCH44TpHYB+Ld6h+63iyzApb8xDNYQmq6Wnc11QD5zKjoW16QSEfuzMbiAcl54OPvSUJvvH7dBGtV7TPDYsloBeRi+VGbOXhhQNLiZqsdPJZAHak=,iv:h0u4Y95iVkXGV1/l77FLV5hQ26RefTa9o8SEDowZZqs=,tag:S2SQ2TgYLDgK6upWQGi+PQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
