apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zt/I0oCURyfU4WeJ85s2e+cc73OCcdStq59aGe5OXEWcOpeCXC6JQ2jRfBB/fT7srRp6czTvGR2FSDuDfA+fC/jyLgwBYcXfvOIGbZNvxcgw+i3qPb8SAMPgrcoPgPgs0ZoIr0j9Acgiv87fNek0pf75ML4pFqNDnN6p1Ge0Ru1wdT3WJEbkiBtz/JbruAU6P8E7JTYgQMjwImWQJtr63w/XqV1X4/1b+6UgQZGU/5ake7xexmjidFEK+r5c/PGq8j9xu6wkUrmJ1JEohP0fJCctXYW1eSl2bqDi24SAGUAOxO1I+l0QeRv2RQnCxIbFgfv0CLJKDx7PtWvqo7A3+G/P6uDUAtm3+vipVNNLuK/d6jzj6Ny/W5zwOayKTR4S,iv:40qxiKoRJvH8LwikBNzHaXXVb8y9RuJs5nhdQPC0Xv4=,tag:9NJkrnHVQO/AYbMIlFXdFw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ONI8mAxaXQiPk9n9wEiX24y8bQR0G+ohhuDJ68aNQn93tspH3j7QY7726ekJWSehtQoVSUtOd1Q3LRwBq0VUM8T6LNQdpkRT7pfqpHPsn59MPsEskxgDU266Hd7IwQBqowbCUmPJYgDYWzBxvQraGTT3xKKzPNzT5T1uiCcxjiNDn1UE6vVp8Y3c6UnLkBNuciL/4B44b0FausSj/MR1syhgrbryrh+bTQTBUI8SV5fkIsVvL2W6QQEkFNQBAkvA8fjeH7qvPcsv0AhGlw==,iv:RSv3QG859W8w7c4nPQR2wf1AcreqHH5dvSqhi5JpDig=,tag:zH4UxoGzgFyXVhthP2/AsQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:s0NBpC5kxVjQdS8y+SmpZaNoKlV782PukjA/XUsTwBV8Ud4Aj43mJ3I9+P2bT8czZ6zUebAKiVBSgTaefA7X7+KQ7WjRmPT0mRXHqmWvWZcaAqkT7qMNDpVCenkYrZhv/Lx3SzFDa5xlPst0u4SruizXlS/5DsqQ8oVkiVIEHTqzAVj6WBHlk5NhuhJDT0Xt+a/4SKmLp6vcIw/Fxt4jBLUpUhrD9KTx8DdO,iv:5V9xI/5QZIlN5c387K/GuIe22OmSQelAXUeeZG4EpRE=,tag:ed1OAFIi3xAH+ZINJJkIXw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRFZOMjRkdjYxMURZMVR2
            R25ET2NDbmVNZHM3OG1ycWhzZHllSEs0QVFRCm0vRkdxQWoxRWtteGJyNVpOd2px
            SVh2Tnc4SnVpQlNDa0ZNaEpIaC9jREUKLS0tIEM4dFhvM0NUdW56THVnU3JEYjRW
            SmVjS3VlOTdxbk1zYjJvUWxXNkY1MlUKDDV7raGZsR2qfYANzTPRjYU/gzHp4PZV
            RNAK4x3zh0ASg3chNWcHtA16egFf9zC44EKMwMbUidzfmzb5hQtiPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T16:16:45Z"
    mac: ENC[AES256_GCM,data:Gr9m2xFkGv7aG3ekr2k+FpgAHcJUYplR3dOoPbkk/7EytmJnUmMBlmoetODGz8Czy4h2QjJfseU45eSV/RGFK6ixew5ft2TGYIfssS17Nfj4PRWkqdC6yuQCAZrQ8xIVRgaqgDtuLRYv5sI2nTSZ4jpmZ+6y45ohh54VyVRyukc=,iv:G1ZJ0YA721JrcrK9tNpt7q9RqR/saCva+4jW/fImG7Y=,tag:NtHaeZ5QVLB7y6KCFmityQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
