apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2e8s3MH9lz2M2P9eobe/b0/pBaA1akAwDkZJ6mKrCLqhuctdmHfA7VZq/McjLZNMClc1Ts1imQAi2BI9iFf3ED7NHnVEnFWkiSQxC4aK5fJaAIHCcdwCKTs4+InYthYTq9MtfpS3wgM4tXWdKlDKTy0Uaz1x89M+efM4maIILd+Wf1ftZxDfWhcEprdhUBd+VU5rvXMF12AKLE8XbKzhuq8bCUdjJVj0O1F3FrqxgN0QivIWX+7JJUhT/vJJCYWMr+dBMUI4oJeZIATkWnwjMGIB4xhe9RUEUYBmljac/4ugyW8zqfrwddE9dWjgfX3/rgNXi400r34xOD1fo/VmpQeQjrQ+Wt9lx1j1N+QGr/+UD3HTJOkIGOcjLDi1JgdQ,iv:PWYdEjjP6YgbG5UUEvUTETI8RHy8f7uBmOPSbJB0B6U=,tag:vtLHT+ReJ4QB42e0w2zxXg==,type:str]
    identity.pub: ENC[AES256_GCM,data:1WpGj7SlYkyE8GtDQ2Xnau5A5cGd9T5TYAlr6AMT8RxXF1T6dkOyBMqw/1FNpwHW7G7CKlM2MS1VMYpIJrQi9VIAu3x4o7uLtqI6pNHlac+7RAi8/b7kFDYyg79BOFSleJBDjyQGY4w2K3RdVGiH5UGrnOtn5qo2/7tTnygruKIwlDL1jT32ANr+dZsOGg797pETLI8cjQFS5drpdma8O6noGaremEf7qbfCnHqXtUORKwt3InuGtt7AsfIAo2RuSYe+kga1G+l4DXLSng==,iv:vrntI5MF1ZPH0HrDDncMvlY+jjFspj18VbMPBZgedqE=,tag:Hwn/tN5+vcqxIquIDGsBNQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:PusGG2iDvq077TNq5nkVF0Z8Mjfu5dqgFxx7comVEI8TxqcdZ05w23d87uhVuoKVXoWNVVsPoTeFEZbCfpQ2OzroFW+lebqKTUbSyU9huKxNR9ubbOckNCaCS1MNtmDbgeMzlx8yaNXFOLwkXegoDQTpY8uHE4WlYNLcdt/ABudVhhhlLSpEogVlPhn8m8bMsC/zC4eeJlIYL+ViaBqtJ97jdMP9GwtgZHYA,iv:spp1+h4N0x6VPibA5e3+bGJ1MwoNXOtLyw7RE6ss21o=,tag:IxlbDddcnYsAy682GMb9WQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NzR0ZE1vZFFKUERKc0p1
            SitqZTFHSkp4Mm9zWXRkVFJIUGxBVUJ6cWxFClNYamdaN2VzZHpzZ1JuOTJETFkz
            dnREZDZWV0d4cEhmbVpaNU9va2FxVnMKLS0tIGFQbzlQTzJLTUtpekl4ZzkzVlg3
            YlJDVWNVVmRRU2FwLzE2cHBSdWNnNlkKOSCzfmXElr6e/hhT2gd/7xOto80nQary
            qnddq/q/i2Cr+z93YNNwv1ezbtUZuSnNabhFVhvEKMk/4Yx08DjOqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T09:01:37Z"
    mac: ENC[AES256_GCM,data:zCd18YY4lpClNN/IT/or0TrFCZCZJhgokhlf6aQrpsnFM3IuHzZkHR+eVopnxaP4WYL1lmYTgER8HT1FECR0A/3YUWsLa1jBFiTr/AimvYQk6ExUOk0Wh529gs0CGAofHKo1nV23YdUL7ARt/+KHM1gzVMRuis61xkI9ZLK+PMc=,iv:m6vlKCrjNpSISjhqraaRd/9xCDyx9K/InIOsYhDbJG8=,tag:HVUA+nN/n3vqCq85uzFB7g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
