apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:B7Wi7yKmpjnUAo6PrjQAynCrCwJ2QEttodiMVkWyNZPeI6aA1a4jfPjB9WJW8aQl+Qya20zXwspvqXOFQGKId/7kfcH+6XjwZYTftuMQWJTGGNsZjaliyE69vyjYPnX5KidjHr+Q2K/5rbe9A8zMllWn0izKFE3NsUYBMMa+TPZsiVquKYzrraIv2QTc0nFERMqUjRT+N9xOcXvU1Dm2ifpVnib807Ec14Vru/wp0tAEHH/ZqFM6x7ZFRQiocTBifHSqEyNGHDsoNssMrs4V5BH9E8h6Pxvi5ZSTPwVqhrKEIWTiYy18VhYSDSpVdjdVIujbPxjxLwekwx2oMkzM+H1aYDSyf/DDSRFY7EoRM4S1KLEo+aByaDoQo/1zjRJq,iv:M/PWR8OAPRY7vq3D5q0EWszVsrIJi1WQ6QMrcWNUuS0=,tag:Wkhia1nJdJvAmrFg9/DGCQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:1x8uODYMALAArZsTAVooxgCSKKWhpXpqEUKbTxzYSanOAWC5Yf5/YsdCK1fbsr2Rh8ki60MKMSHq5Hw+o/w2xl/3jtFIo1ly00gjh0g4v4v1fuBWo3962WrIMav4rKhDOedDB0/RxjXUmIqV0qFYhg61dGZRqkzU2KWNdHjRaVAEyn2Qn4T1iVGNQMtfjQ1yzyZGDOoigTtLmRuyNmtNBVzY7Ow3bORHt/z7aEZUBPFkP89e4PUf668TcaC3KYCOcfJKhtJHToiJlsSbfg==,iv:zASDq+7xLeYCFKGoh76tllgbTuk+Uo3GG+FmjggBNn0=,tag:7WrNQERngQMSmrukFTU6iw==,type:str]
    known_hosts: ENC[AES256_GCM,data:THBgE4GF5UbofE/EeB5mklmbrmRJdWE5XlFaJe8sNGpairwp2vxVNzjvej6GWkJrkSkqoi8CeeB1tCHUkBLXdhytYyF85WLeoJ+sKryzBOr3x8Nq+6Qk4v6liNz8jpPTTkSCL80TDb4Hb9AqsSw8WXVrVcni0tQs7vHMZ/SC8dJ4npQ6YKuoE2CKnT812EBvof8I0xLxVNkXix+WnLJdJ22kCoyOPjxsohzA,iv:QdR6eWROrFPmelQcCiCZnD+7xiATvJoGhaLVndS6ht4=,tag:DKr4IdUMxjdynLplzeb4Qg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUTJibTgyTXpBaWNBSGQ4
            R3hhQ1IvMDI4MUJYQ085VDFTQ2VXWVBOQlM0ClhocGgza3VXZk1aS3hjSnhnUXA4
            WEN6ak45dE4vTi9YN0ttUFFKS0ZtbmMKLS0tIHlTTUh2K0wzOVBQWTRONEpCdDNX
            cWQ3dVFWQ0Y1RHo4YVpSdWxhRlpjMjAKcJUfVlcO6xvxxrxVIqFx1DV5aM0KzV1m
            HXbHzBYb6j64x/c9/WfKN9JXIsrEhSJ7Ie9ycEGW2xVw8koKW4DzJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T07:44:18Z"
    mac: ENC[AES256_GCM,data:5my16qDH9HTMkSyYeRnN2IvJ7tKTRqvkAtGn63AzsWfola0kAK9A9pbnEJ9+m5cX/3gg1SxQSuDKVSOffyFif+L2kSlkcV54be4WXP+imdyufOLtSJVz+kv7YvXmbvfNr8e3FlBezXsin1OX0/fmLo6eGojVxkCjn9J9c/2zpfc=,iv:sujNR9cf+oTDAPQKjmGm6Nvv5cC1/IcMeBKPwaexdys=,tag:gXqtvSOi6bcMgSsLumBLAQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
