apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GuovbmKwQ7zrVm3S6/0FoJAo2cpo7EMrUFvYygp19t4Yz0Wvlsx2RP+71HphOohA5J+9dwxohWJ7POQ1XqI4wuY3V2Ht1jOCvqByg7qMtr50o7VDboeQMdbW953tfZ3K8wDLJfTXewBGxW0NXOaxa4eFRPXDL+KDbeDvXgYHHuBI+CgB+JGQfftkr6XTU5RynSEXTuBzLOPcu2X2ODbhuxgvvdxlNl9PoZDZhnil57fEDnmUBpua16DhsEcbzDlYR0yeni6Yq/jK+0jWfAT+Y4NQhVN2mrWT+WRsH+zMfY0LNaS5wyIn2n2oWDJk3DgvgFzjsiiGObByRRwS5TTSkegxdJeMlXvjjZdr49CcYuE8/XUV+iXh4exsc6qbVXmh,iv:KjRhta8sCivT0hza4Kajei9xEbfw9+tVqyeNh3+/i7o=,tag:7Q80uzTndnyzH1w/tOTv6A==,type:str]
    identity.pub: ENC[AES256_GCM,data:pDmOfTC64UnE0p0LXwhw5tYyNotEF6xHeiv+XRjX5Ook+U6nx+uHNpFA2yS9QUNgi6UEVMuZBTeAf9SLledBuAAjAmyyAgK+FNWAeE4VMj7pmfz7mefDxOA2WnbgGutoG9pPItiT+Wh1lJ1laCiVTh8sh/DKr6ceGmznh4xo4GrpumtoCnjKiMSrp8m2TdTveqmlQlVrp+hOeuDTJpupICJ6tNgHWUVBC8B2CLosqneZZ3FErYp154xAjIAYvwk6NCAxrwU74Z7bIlyWVw==,iv:MSTD0x8DhfLi4PrYmHabdDn/0x7hnkIPrAMGuytBnGI=,tag:w228MUOf5J8DJDzm9cELmw==,type:str]
    known_hosts: ENC[AES256_GCM,data:JNuCy7HRoFuihTaRPQJUYCR5ytbTN4bWoCfCgg2hMSwWc6FEDkov1eOqQCWLdBOiJS76YTCluSkh+NxcAB6IU+0UQpYyd5PT/mnEsqULYYpw4BlrVknhHG83Un/K855iim0HxXeHfl/zDE0lRyf0Wy2WX7b9vBoMNSrlp1XY6zs7eNpKo0+X7l/bgccNIWTQwDg4RIz/buHyG4t2SIfvfpzPu5WyWPzo4ywW,iv:zMxxxQeE1PFlHoqiPoWOOSEOPkjuvV4667Cjmz0pcZI=,tag:Xrtx3PQ1+1yalFtWiqejAQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNmRQSjA2NkxTSFBuT0Va
            OE1kOXV3alIyeW12QytjN2RPODRuRHhzY3hnClZNQ1FEVjN5Y21YNHFFQUluMkZh
            TG5pRlpJQmY2bTAxSmlieVVTbHBMSm8KLS0tIGdhaVI0NTBSRTJhdmtXUGVlZVc1
            azNYV0ZGRFE1b1hTSDJzN1JQWjkwYk0K4d7zVzn6zu6A7f5P0Jh/2uhMqPQlbnq5
            SHB+sCC0oJ4XRZIP+eIQFP1ASZoIl0FzEMaPwcETrdHnUx6Rin9pBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T12:33:08Z"
    mac: ENC[AES256_GCM,data:63g7gpTFFYsQoigMqAcSD447DvvatoKMtgXsG5kstt6yXErXq1xIJxio3AXNJ3U55zs9oFZceIAseoAmyzMDLn1bwrLBtEn8385vSEd8udJ21md0Hy8e/Kpz3fhClMiYrBRVQHt/VbUIMtcEj/2ZbjMEtDKPBl0t8Fg8Pmoqyzg=,iv:2Lgymi3Ppd5Kfhu+msaOZu4WQW0kz+vTWVecDAAedgc=,tag:Ojzb2Bv7a7Ia5YYHRwgwWw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
