apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:kZf6PKVUeifbRfJFW+jnZEZMMOpisC/lUUYTSW29kwH14UMeUDgYdyye5sPuecgAzSLxGlq7B+/QZqeVqXGf9SzfpsuYWJ90Di3vxh+NlKY163VHqLGODKn2YWo+rzijqgK5JgC6RKXb753R1Xkds7n3/4ObQMC5ZkL6CeZI/Owag5P58baQCQ+ibNiNsLLzpOmBPrCJWblna9YNc+PSIMnxGrC5ZaiNXUldYaltCNow7kdMsIyWY/qRAi0YTHd9+Z0zwYAw/YsIlOWlaunoZ5BwkxW0RP1hDATu8U/ISBlXycXIiz1fyO3zbWeuNVKNpZtJt7+dvPlN4CnbaSQ6lebVrs0WpOYldlb2E/SlvzBb9L9wsy75E9NlVZlFiVBm,iv:LKWnSq7UvdANM8iCm+JxWV1nSZkXM7qjGHtjJqPvhqQ=,tag:CN7ABW59HUgdVUWG4XSYUw==,type:str]
    identity.pub: ENC[AES256_GCM,data:FdyuFvKMi90lHQAFONZSEvUYgLvufb5mK+7ULBjiMhEx9LNxyaPoBOcRE2InD//feXRJhKNX4Y+xX8H7iVvioPNwCRQyE5PAQmFvkfa7J0uzcprOrstR0USV1XsvzZLGDpgyeYjtAtMVttj46poMROSL1eTdYBUkI5A03uUnlOYIjsuxgg99zAcNcnQ+bofGdeeNhFAvGSOvYGjt4/NujDCrUIhpJDPKzd8XSlQqCvKDYTZRZn2e/PV4GFZuX7MpDjvEMlaj5tsQRJZO/Q==,iv:9QXIUIlFcVKvArjW54RwYENDn8IQWPptGEadGjy79xQ=,tag:LKtEzQQ5JHBhggsAjV6UQA==,type:str]
    known_hosts: ENC[AES256_GCM,data:mlRi5YHAIOc/4pcb/o9vHowTvSZqNQp/JVDUWexVahfrMWORsLW6w4IDgkpxiFhrX2pHh3W48J/nFb0TU/iG430AvR9EzhMUJCjpElM+GvOe/IjlvA5QJS736/vkMRrcXMG2Q+ro5FQ0a1q5fdkRx6H/JsQ+L46Q++0RBrzUqKsEwK856O0e2KdniHtYx2uNfrYvzz7q89NQb7R9DM077bjRKSAk1MXS8nCJ,iv:7hXnOjjhK4YK1xODlJSs+hNarzKDzBUiOtMqgSBv2yQ=,tag:ypBQjUCvA1IXVlwNVpNalw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbk1POFpDYkRVL090YkdV
            YWVCRWpUMEp0ZFNkbWJualpyU1ZRWjVRWWxFCmIyOGVPdkFjQzN6VVpkS2dpdkVr
            V3AvOHU5OHdlWlVlcDFxcEkwMzNISTgKLS0tIGlheGJMdHZnVXNPNDBQajNFdm5F
            M2MwR0tyVTdvaWlBRWcyaUtvUFZTc00Km+KJQC4k5+aTxTO5XUNBmXTIjnSBhu3E
            fweO/tHjxr6MxfojbVFpSyYm5ZZcl8sVI3qxAx9B5By58dknq4obsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T06:40:14Z"
    mac: ENC[AES256_GCM,data:a7Y7TxW93BEK5qkFu5PYvmHb2eS7RH59hN1hzg0x44+SgP8dTu0D0j9yxL2KEVle9MHNMNTtcejov5uMSkwqaiuMsvDB/wj5ZqopxGuIze5rV5Ynxmoz6e4hxuTEmG+3JBjbULBwRxCxSDKAgOk0+qb3h3LZ8m/wuyfpyIctxjI=,iv:i0Cnmo2ybz31xFCMsWOLyUalwsYxqVxomi137ZxIwMs=,tag:3p+RRFzCBZE78MPHd7n4fA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
