apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:XQgturyutoXyvsYkb+zcY1sco3JOjChBK3bVGLlb662YCRE8oFL7ysoz4xbWap+gs4y9q3p+mWUuPYDo8qyS6Jy9Fnb5+D1Lc134odY0qk/wAt3r+LKFL/esFfiTJalv2S4u6scRQ971w5FDdKyRtLdpX+h+MYbmPbAwfpGaiG/SDiwtpq3F7Dpo6kybYHi0Ajyisu+wOxzxe3Fy4kEBWg9tVOuFCk8AWmfP+vMkPEiQA+HQNWx6S6O3+SKrXCyYtaGPBEZJT2uFpM8q4rIH+bAWKZmmt1HaeBGg7eRk+qdq+M63JOWRc/MSQaTISB0fHfbrWr4lnygZ4SwOkFBpRu5tnTLpZ8p2heCDaKq6Cmgk6oWfFuVY/qhX6XUvvz+2,iv:3jo11ShV+9njLna54dZyoVI6QFsTBD3GSrQHxvNEMUw=,tag:OAHBYvid4d4h86OVvZ51gQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:tWlORqWrS4u96b2KaRLA8c6Xr6MKRNUooTx3BQjFgGJc77A/i9BOgGIkj3U8Tn5usG5t96eX2e7JjPd9Zf3W1WqohR7aNaYeOVFNTAuOBgcP5xO8Re0TMwCycSuMBgzbeisOBXjXh3OUd+GV6kJHqjByD4V+5LCbc/9/PAGJsWE8yDYfNHeBYTlqy5CrZVX7HIVDueJDlOQDvej/lJzQx1HGPWVg3LNB4P4kzgKM+EGcYJYsGGOWl3ETX46L6RXbXfrHnfACK5GYj6RT1g==,iv:l53FwOz5DHIcFzD59p/pSsxHbl+lnQDfuj2mIoQf834=,tag:5+04aYGC97bbZAoIgptBow==,type:str]
    known_hosts: ENC[AES256_GCM,data:TFS9tTsBBRssIQD3graCTnPJ2c+5wTDwK796MAEqcYg7P7CG2vZsYePvtdfJyoPQRNtanSCBOmRjh+gNuMugqFeeYy1ORcTCzF2gV0Dk5v3Wm/z6YJpQ9NVKXkK7SlGeOz1d4WjtWM1HWsuNC8yOUfFKKQ8UOjf0fGZTjiMCHqgP+03cw2GXpXQAJMU6OuIcX/NuTboSjZmye2dYOMPGQ7jk9Umado5pVoDh,iv:67u4RCr1THlFIVkAhvsp3wTztm0/ZhZdRoWt+ETIl6o=,tag:fhuo/oHhVfn5ce5ddJHxgw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOHZoUmxPSnhaOThjc0Zz
            V3pvZVFnOTA4WFVIWWhRLzE1Z2xmT3l1L0RBCmUrQU9MRHpJalN0alRjNmVla0Q0
            dWZwQ28vVEdEbmxldmdJWndTMGJrR0UKLS0tIHIyUktkNzlUaml3TEkrNUJHTXZV
            WDFtZmFvVmE3VzBFbHBodXowVjlmOXMKCkViNzS1r6rynTBx+n708WYSoRz6Zusa
            z5TVyw5yPqTZ+TqSs/WWTSdUzpqE0M5RmaUNvAPXwSqkkVuApUn2Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T10:53:19Z"
    mac: ENC[AES256_GCM,data:PouQdhTd4QVpJLgwnbf0isFH0lazW5qhnvdLfYWF7vsCMH7KUk2AbOkw2smjA/y+RZf0OC44Axy8mwhkzFn0JZFpDw9/BpLPZiHoV4QEBnGRyEBuDWunMtABzvm/5XiMSMi0IylqiV3crOYx+SCmfPLeF1RnYH7hbpk7MN7n7p4=,iv:pXoxlayaW40S9KXAk7jiQVYzza6vYGL1EfTaNL4SmOI=,tag:w+5VVmqQugASZMhwPl0RFg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
