apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dtTayFWQNlkojfxWAn7Vczx+8eU5ams3jxFdyAbc+VkCuI8mqaKNuDg84+hyeu0rqHWGlNQGn3NazpSkKPg/IKsim0fe5t2ybNFEC0GaFCfyC0K+uv+If4uWiRyxnkDMHOAa8OgCTFba5Heu3QCMil7WeHJJSVzeEh/2Bc20+PTN01nmh2tBVyMceO0BDUaXPyxx0xM65bss+XXWRQOhb/kY7A1DfyI4vDe6WxV7n7RVGE9b2G4c4WOKPavgFjOFNfRlzys18Cg7ykc9n2jbfX1VgnTYtVcwRO8Q8qPFW1B0mLAvyVH6HbLqdUdqXfWh37iyo5DVMIn53wjaEkky90y0OJaNeXA5hoYHn9Cbti0NV7hzMrvKQkZJpI/yt0DA,iv:I+8dniMLlLU/pU+UbXs0MEvmmvWUrnlvTQy01t/qXpM=,tag:GlWnrwFY3MN6G71bXBmWPQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:798znz0L7RwC+LqnIjvEE1bS5l1ydTQ4DEXzf399m0geckwBRI8jvzz7hX88YsGVmoSN1LRevBHHuUhSlSg565ccemNAoFZedZ0pJ/XYMJLlQLvpak+eIAei1Da8j3xiMqbvpC1QqOOhNITdQ7yMO5Pydnpov2SdTAHg+EpOBJ+matWVLazdSDAifvpyQv+0Jax+cI/sYc/SIuD0vbc3ClUgcU8DGVoNxEuuU4dfK2FaPVfSCfiHovDD22gK9qtVIejCurj2rkXKttvSHQ==,iv:Y7xm7jqBFP8urfzDgdRT2W1ro337zaHk4r1FiGtWzl0=,tag:957B6B+RESP1p39n35dnxg==,type:str]
    known_hosts: ENC[AES256_GCM,data:lagHX7DC9INZSy8myVC/TucJ1DQ/7FIBJa2KZRIAg755XbTO1mw8INhNldZAqVnj3xCrZcyH8DsCOVvOaAK720CNocNcDr5mb7fSOk2hyKTO1mQPtvIMz5vZh8KuO+bU3YjtUcwuFLv4XyPIiY2phHNivHSHWuDg6yacL50a1vegSvkbVKKLnTd3Bd9oy9O/9C2dS3Dplu4zqOTqCm7lizmoaD+d8m5Vp75j,iv:pob4j2zLiD0kBfD3gbCuPJR7O60rQuLPlaWMep2KpAU=,tag:81WXkv8DXGtSZlI7TG22vQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ3ZYVUkrczlQVWNMenRm
            U0tTSS9ZTEFVR0VQeXFnWVU2akV6REtYVGdBCk9yV1lvczdGRDJ5ZWh0NTlXVnFZ
            N2M5TzB3dElqcUZXNUZQc28vRXpkeGsKLS0tIG1KQnZnY0lSeldsUjVab0lyS1Bq
            SU1CRklzT2FTc2xWVzV1MDBGZ2x1bEUK62YdoTk5MEiLuZnSTaA9s2PNY0iEh5a4
            5fHSirIWW8wHv7PoGl3zMJb8ir1rTf44S1YKmgUr3Qw8OM37TigNuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T10:46:44Z"
    mac: ENC[AES256_GCM,data:imKTzk60XIFiGmH5+8RGUCHI5hm8+Ti0SSeFtXKNoBwLkXvAZv7CrotfZnYsHAkDt01ge8+mITbuS6tK2v62SV5l5oB3VymqIgfsXCjJ6iKrOGyhK1xO6DETq3Hy93unFYcKNClw5gEpR/nHN4JjZJJr3echUyopWz9Yjiz9FL8=,iv:YGfpF9Q8ACiJlOULqIsxyRyroT2xqPmxoIqxLK3mrmw=,tag:GFcvJ1RDfNSLx8Hv9FXZdQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
