apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GvcAHzuXnSuFYSog7DnewS3vGTKzZttzwyUJmz7NZ5Hwe/Q0xnu4T36c81ehzSzfiLlDNbUgOmpTCAlwBA15HrDpW2xngIhG+yNssJehDfAjkk3rgXipDuK5foqioQbbJR62yyL6VKvdBA6AaVgbunPSAPgY1/Wy2MDeBd6vCVIYSisSJ3uhZCKAMvqrXN7/BLtLfInqE3Cg81xTiWB4LpC545GrcJbxYR0TfpZSvPk9nu9746+ehHJOAT/opp5C2MJUQFpjtCs1Ktm4gPbUM26BBalhD7OGN++nquEQA2CqD4BlwddbSp6uVqg8jzPkPlBE8U0bZO3uH0A+JwLG8aheO2niJWxHNYjcOb4ufu7MCcUnZ1Dxn/mrq94CINIE,iv:4b0xGA7mevl5/48NxcxS93im6FCaY/HB44d5zgmdB/M=,tag:w34Hvo3wl4dwoK3mbDIKVA==,type:str]
    identity.pub: ENC[AES256_GCM,data:2XLg4zvdz1klq/dp9OIBQB5YM3K7sCvn/aDa/upYP3DDBzHyLo6wsUhv4oQdjQnJDbTe5WtoGiC/os+/D3yFKQOvZ+OCW1K1p24W2w7N4C7vuFahBqWqBRytt/G9zdi+GlkBxoHOlt6F/D92yUPKKDOHFsbBKNNR8ud9/c1ky5seEBkEeKqzBpn1w0kMohb1hxVh0yM5isKQMDn2Vz9fVo5zsx9qNY/IqRi4SGHCtCseOeXKxmfc7AorKzQONEDjP6OhwxVPx1eKl3Au8A==,iv:yYuGqlAG4HNzeszuFw77f3AVRINDW0WJxp8/meTjdIM=,tag:Va9gUwX735Uo89AdfQAc0Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:f8PjOzL9Zz7zr/Y6FwE6JvYIE3FQRClKHao7KPu88xkHB3Du08HKUTPF6J00q7hhfCj8GhFw30jVk5FfVZ5QBrgB1mQO97KWzrpnCNxnvYfPXuKNcWbp4tK30LW489382T2+V8UfTVVvejJ7xUP7KlD1RUn+Nw4oIXXqWdhe0/6kywwsQN6XRKAt5iPWEzrdw4rk5hVsG1YlYzxD2Rc7NLPPdttXAVVVUrk4,iv:RxrB7Q9xPZdLtXVHVX9RVWaLYS40L8KnuZmSA4SgSgM=,tag:zTgCl4h82eWNIuieH7LJ4A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcDl3a08reHduZ0xDaTFx
            MUhpZm1WVm1qMG5WclUvR1paV04wd2Q3dXlVCm4wR0M2M1Eycm1zYUh5NXY0TzJk
            UXBVNHNCeit0WnFoS0Fsek5EQ2R3MzQKLS0tIHFaVW1veUlTcVZsNHNRRWZvY3d6
            UjlFeDU3d1kyWWNVN2txalFkMGFGWXcKwOgXEFr+O7slhsmaXNhqWD9hIDdibPX9
            fH8NX8PyLMkmTCM6HlUY6i5qSD8bswzntkxdm+VyB4eHhzKMTyc8QA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T09:34:12Z"
    mac: ENC[AES256_GCM,data:u6JZU9ne13JPl/EU25aZTLKndSliFXVtrKI2W64k1NV7Ph5eWZgpS2mkid5efS9mmtCNkoGktPqaEk5+JICHwtpoZTeRHtK0fvUwDmKv8fX5H7xd62K6W79ROPxB8Gn7gerLtL2O7ZyaZtviczDEAv1k7zu0kV50eG49s5qEmjc=,iv:4+pLGM79b12yEEhHmTSzctmM39fnD+Ux4615rFLQTeM=,tag:x6jB0En2RUWxNxmFprCTUQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
