apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-cleanup
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 20 18 * * *
  groups:
  - default
  name: cleanup
  retain: 0
  task: snapshot-cleanup
