apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: trim
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 30 18 * * *
  groups:
  - default
  name: trim
  retain: 0
  task: filesystem-trim
