apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: helm-repos
  namespace: flux-system
resources:
  - bjw-s.yaml
  - cloudnative-pg.yaml
  - home-ops-mirror.yaml
  - jetstack.yaml
  - kubernetes-dashboard.yaml
  - kustomization.yaml
  - metallb.yaml
  - node-feature-discovery.yaml
  - prometheus-community.yaml
  - spegel.yaml
  - truecharts.yaml
# more goes here!
  - nvidia.yaml
